basepath: "github.com/pensando/sw/venice/utils/apigen/templates"
templates:
  - template: "doc.tmpl"
    outputpath: "{FILE}_doc.go"
  - template: "endpoints.tmpl"
    outputpath: "{FILE}_endpoints.go"
  - template: "services.tmpl"
    outputpath: "{FILE}_services.go"
  - template: "transport.tmpl"
    outputpath: "{FILE}_transport.go"
  - template: "common.tmpl"
    outputpath: "common.go"
  - template: "grpcserver.tmpl"
    outputpath: "grpc/server/{FILE}_server.go"
  - template: "grpcservercommon.tmpl"
    outputpath: "grpc/server/server_common.go"
  - template: "gateway.tmpl"
    outputpath: "gateway/{FILE}_gateway.go"
  - template: "gatewaycommon.tmpl"
    outputpath: "gateway/gateway_common.go"
  - template: "grpcclient.tmpl"
    outputpath: "grpc/client/{FILE}_client.go"
  - template: "grpcclientcommon.tmpl"
    outputpath: "grpc/client/client_common.go"
  - template: "extpb.tmpl"
    outputpath: "{FILE}.pb.ext.go"
  - template: "apisrvbackends.tmpl"
    outputpath: "../exports/apiserver/backends.go"
  - template: "apigwservices.tmpl"
    outputpath: "../exports/apigw/services.go"
  - template: "genobjrelations.tmpl"
    outputpath: "../relations.json"
  - template: "crudinterface.tmpl"
    outputpath: "{FILE}_crudinterface.go"
  - template: "apiclient.tmpl"
    outputpath: "../apiclient/client.go"
