// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoint.proto

package netproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/pensando/sw/venice/utils/apigen/annotations"
import _ "github.com/gogo/protobuf/gogoproto"
import api "github.com/pensando/sw/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MigrationState int32

const (
	// ui-hint: None
	MigrationState_NONE MigrationState = 0
	// ui-hint: Start
	MigrationState_START MigrationState = 1
	// ui-hint : Migration done
	MigrationState_DONE MigrationState = 2
	// ui-hint: Abort
	MigrationState_ABORT MigrationState = 3
	// ui-hint: Migrate from non-pensando host
	MigrationState_FROM_NON_PEN_HOST MigrationState = 4
)

var MigrationState_name = map[int32]string{
	0: "NONE",
	1: "START",
	2: "DONE",
	3: "ABORT",
	4: "FROM_NON_PEN_HOST",
}
var MigrationState_value = map[string]int32{
	"NONE":              0,
	"START":             1,
	"DONE":              2,
	"ABORT":             3,
	"FROM_NON_PEN_HOST": 4,
}

func (x MigrationState) String() string {
	return proto.EnumName(MigrationState_name, int32(x))
}
func (MigrationState) EnumDescriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{0} }

// Endpoint Object
type Endpoint struct {
	api.TypeMeta   `protobuf:"bytes,1,opt,name=TypeMeta,embedded=TypeMeta" json:",inline"`
	api.ObjectMeta `protobuf:"bytes,2,opt,name=ObjectMeta,embedded=ObjectMeta" json:"meta,omitempty"`
	Spec           EndpointSpec   `protobuf:"bytes,3,opt,name=Spec" json:"spec,omitempty"`
	Status         EndpointStatus `protobuf:"bytes,4,opt,name=Status" json:"status,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{0} }

func (m *Endpoint) GetSpec() EndpointSpec {
	if m != nil {
		return m.Spec
	}
	return EndpointSpec{}
}

func (m *Endpoint) GetStatus() EndpointStatus {
	if m != nil {
		return m.Status
	}
	return EndpointStatus{}
}

type EndpointSpec struct {
	// VrfName specifies the name of the VRF that the current EP belongs to
	VrfName string `protobuf:"bytes,1,opt,name=VrfName,proto3" json:"vrf-name,omitempty"`
	// Name of the network to which the current endpoint belongs to. Required
	NetworkName string `protobuf:"bytes,2,opt,name=NetworkName,proto3" json:"network-name,omitempty"`
	// IP Address of the endpoint in CIDR IP/Prefix format. Required
	IPv4Addresses []string `protobuf:"bytes,3,rep,name=IPv4Addresses" json:"ipv4-addresses,omitempty"`
	// IPv6 Address of the endpoint. Optional
	IPv6Addresses []string `protobuf:"bytes,4,rep,name=IPv6Addresses" json:"ipv6-address,omitempty"`
	// MAC Address of the endpoint. Required
	MacAddress string `protobuf:"bytes,5,opt,name=MacAddress,proto3" json:"mac-address,omitempty"`
	// Specifies the name of the node where the endpoint lives.
	// Optional for LocalEPs and mandatory for RemoteEPs.
	NodeUUID string `protobuf:"bytes,6,opt,name=NodeUUID,proto3" json:"node-uuid,omitempty"`
	// IP Address of the node where EP is local
	HomingHostAddr string `protobuf:"bytes,7,opt,name=HomingHostAddr,proto3" json:"homing-host-address,omitempty"`
	// Microsegment VLAN for the endpoint. Required only for Local EPs.
	UsegVlan uint32 `protobuf:"varint,8,opt,name=UsegVlan,proto3" json:"useg-vlan,omitempty"`
	// Migration stage as expected by VCenter
	Migration string `protobuf:"bytes,9,opt,name=Migration,proto3" json:"migration,omitempty"`
	// Mirror sessions, if mirroring is enabled for this endpoint.
	MirrorSessions []string `protobuf:"bytes,11,rep,name=MirrorSessions" json:"mirror-sessions,omitemtpy"`
}

func (m *EndpointSpec) Reset()                    { *m = EndpointSpec{} }
func (m *EndpointSpec) String() string            { return proto.CompactTextString(m) }
func (*EndpointSpec) ProtoMessage()               {}
func (*EndpointSpec) Descriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{1} }

func (m *EndpointSpec) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *EndpointSpec) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

func (m *EndpointSpec) GetIPv4Addresses() []string {
	if m != nil {
		return m.IPv4Addresses
	}
	return nil
}

func (m *EndpointSpec) GetIPv6Addresses() []string {
	if m != nil {
		return m.IPv6Addresses
	}
	return nil
}

func (m *EndpointSpec) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *EndpointSpec) GetNodeUUID() string {
	if m != nil {
		return m.NodeUUID
	}
	return ""
}

func (m *EndpointSpec) GetHomingHostAddr() string {
	if m != nil {
		return m.HomingHostAddr
	}
	return ""
}

func (m *EndpointSpec) GetUsegVlan() uint32 {
	if m != nil {
		return m.UsegVlan
	}
	return 0
}

func (m *EndpointSpec) GetMigration() string {
	if m != nil {
		return m.Migration
	}
	return ""
}

func (m *EndpointSpec) GetMirrorSessions() []string {
	if m != nil {
		return m.MirrorSessions
	}
	return nil
}

// endpoint status
type EndpointStatus struct {
	// Endpoint ID in datapath. Valid only for Local EPs
	EnicID uint64 `protobuf:"varint,1,opt,name=EnicID,proto3" json:"enic-id,omitempty"`
	// NodeUUID is the nodeuuid where the endpoint currntly exists.
	NodeUUID string `protobuf:"bytes,2,opt,name=NodeUUID,proto3" json:"node-uuid,omitempty"`
	// Status of Migration of the endpoint
	Migration string `protobuf:"bytes,3,opt,name=Migration,proto3" json:"migration,omitempty"`
}

func (m *EndpointStatus) Reset()                    { *m = EndpointStatus{} }
func (m *EndpointStatus) String() string            { return proto.CompactTextString(m) }
func (*EndpointStatus) ProtoMessage()               {}
func (*EndpointStatus) Descriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{2} }

func (m *EndpointStatus) GetEnicID() uint64 {
	if m != nil {
		return m.EnicID
	}
	return 0
}

func (m *EndpointStatus) GetNodeUUID() string {
	if m != nil {
		return m.NodeUUID
	}
	return ""
}

func (m *EndpointStatus) GetMigration() string {
	if m != nil {
		return m.Migration
	}
	return ""
}

// list of endpoints
type EndpointList struct {
	Endpoints []*Endpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *EndpointList) Reset()                    { *m = EndpointList{} }
func (m *EndpointList) String() string            { return proto.CompactTextString(m) }
func (*EndpointList) ProtoMessage()               {}
func (*EndpointList) Descriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{3} }

func (m *EndpointList) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// endpoint watch event
type EndpointEvent struct {
	EventType api.EventType `protobuf:"varint,1,opt,name=EventType,proto3,enum=api.EventType" json:"event-type,omitempty"`
	Endpoint  Endpoint      `protobuf:"bytes,2,opt,name=Endpoint" json:"endpoint,omitempty"`
}

func (m *EndpointEvent) Reset()                    { *m = EndpointEvent{} }
func (m *EndpointEvent) String() string            { return proto.CompactTextString(m) }
func (*EndpointEvent) ProtoMessage()               {}
func (*EndpointEvent) Descriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{4} }

func (m *EndpointEvent) GetEventType() api.EventType {
	if m != nil {
		return m.EventType
	}
	return api.EventType_CreateEvent
}

func (m *EndpointEvent) GetEndpoint() Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return Endpoint{}
}

// endpoint watch events batched
type EndpointEventList struct {
	EndpointEvents []*EndpointEvent `protobuf:"bytes,1,rep,name=EndpointEvents" json:"EndpointEvents,omitempty"`
}

func (m *EndpointEventList) Reset()                    { *m = EndpointEventList{} }
func (m *EndpointEventList) String() string            { return proto.CompactTextString(m) }
func (*EndpointEventList) ProtoMessage()               {}
func (*EndpointEventList) Descriptor() ([]byte, []int) { return fileDescriptorEndpoint, []int{5} }

func (m *EndpointEventList) GetEndpointEvents() []*EndpointEvent {
	if m != nil {
		return m.EndpointEvents
	}
	return nil
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "netproto.Endpoint")
	proto.RegisterType((*EndpointSpec)(nil), "netproto.EndpointSpec")
	proto.RegisterType((*EndpointStatus)(nil), "netproto.EndpointStatus")
	proto.RegisterType((*EndpointList)(nil), "netproto.EndpointList")
	proto.RegisterType((*EndpointEvent)(nil), "netproto.EndpointEvent")
	proto.RegisterType((*EndpointEventList)(nil), "netproto.EndpointEventList")
	proto.RegisterEnum("netproto.MigrationState", MigrationState_name, MigrationState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EndpointApiV1 service

type EndpointApiV1Client interface {
	ListEndpoints(ctx context.Context, in *api.ListWatchOptions, opts ...grpc.CallOption) (*EndpointList, error)
	WatchEndpoints(ctx context.Context, in *api.ListWatchOptions, opts ...grpc.CallOption) (EndpointApiV1_WatchEndpointsClient, error)
	EndpointOperUpdate(ctx context.Context, opts ...grpc.CallOption) (EndpointApiV1_EndpointOperUpdateClient, error)
}

type endpointApiV1Client struct {
	cc *grpc.ClientConn
}

func NewEndpointApiV1Client(cc *grpc.ClientConn) EndpointApiV1Client {
	return &endpointApiV1Client{cc}
}

func (c *endpointApiV1Client) ListEndpoints(ctx context.Context, in *api.ListWatchOptions, opts ...grpc.CallOption) (*EndpointList, error) {
	out := new(EndpointList)
	err := grpc.Invoke(ctx, "/netproto.EndpointApiV1/ListEndpoints", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointApiV1Client) WatchEndpoints(ctx context.Context, in *api.ListWatchOptions, opts ...grpc.CallOption) (EndpointApiV1_WatchEndpointsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EndpointApiV1_serviceDesc.Streams[0], c.cc, "/netproto.EndpointApiV1/WatchEndpoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointApiV1WatchEndpointsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EndpointApiV1_WatchEndpointsClient interface {
	Recv() (*EndpointEventList, error)
	grpc.ClientStream
}

type endpointApiV1WatchEndpointsClient struct {
	grpc.ClientStream
}

func (x *endpointApiV1WatchEndpointsClient) Recv() (*EndpointEventList, error) {
	m := new(EndpointEventList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *endpointApiV1Client) EndpointOperUpdate(ctx context.Context, opts ...grpc.CallOption) (EndpointApiV1_EndpointOperUpdateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EndpointApiV1_serviceDesc.Streams[1], c.cc, "/netproto.EndpointApiV1/EndpointOperUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointApiV1EndpointOperUpdateClient{stream}
	return x, nil
}

type EndpointApiV1_EndpointOperUpdateClient interface {
	Send(*EndpointEvent) error
	CloseAndRecv() (*api.TypeMeta, error)
	grpc.ClientStream
}

type endpointApiV1EndpointOperUpdateClient struct {
	grpc.ClientStream
}

func (x *endpointApiV1EndpointOperUpdateClient) Send(m *EndpointEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *endpointApiV1EndpointOperUpdateClient) CloseAndRecv() (*api.TypeMeta, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(api.TypeMeta)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for EndpointApiV1 service

type EndpointApiV1Server interface {
	ListEndpoints(context.Context, *api.ListWatchOptions) (*EndpointList, error)
	WatchEndpoints(*api.ListWatchOptions, EndpointApiV1_WatchEndpointsServer) error
	EndpointOperUpdate(EndpointApiV1_EndpointOperUpdateServer) error
}

func RegisterEndpointApiV1Server(s *grpc.Server, srv EndpointApiV1Server) {
	s.RegisterService(&_EndpointApiV1_serviceDesc, srv)
}

func _EndpointApiV1_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.ListWatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointApiV1Server).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netproto.EndpointApiV1/ListEndpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointApiV1Server).ListEndpoints(ctx, req.(*api.ListWatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointApiV1_WatchEndpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(api.ListWatchOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EndpointApiV1Server).WatchEndpoints(m, &endpointApiV1WatchEndpointsServer{stream})
}

type EndpointApiV1_WatchEndpointsServer interface {
	Send(*EndpointEventList) error
	grpc.ServerStream
}

type endpointApiV1WatchEndpointsServer struct {
	grpc.ServerStream
}

func (x *endpointApiV1WatchEndpointsServer) Send(m *EndpointEventList) error {
	return x.ServerStream.SendMsg(m)
}

func _EndpointApiV1_EndpointOperUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointApiV1Server).EndpointOperUpdate(&endpointApiV1EndpointOperUpdateServer{stream})
}

type EndpointApiV1_EndpointOperUpdateServer interface {
	SendAndClose(*api.TypeMeta) error
	Recv() (*EndpointEvent, error)
	grpc.ServerStream
}

type endpointApiV1EndpointOperUpdateServer struct {
	grpc.ServerStream
}

func (x *endpointApiV1EndpointOperUpdateServer) SendAndClose(m *api.TypeMeta) error {
	return x.ServerStream.SendMsg(m)
}

func (x *endpointApiV1EndpointOperUpdateServer) Recv() (*EndpointEvent, error) {
	m := new(EndpointEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EndpointApiV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "netproto.EndpointApiV1",
	HandlerType: (*EndpointApiV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndpoints",
			Handler:    _EndpointApiV1_ListEndpoints_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEndpoints",
			Handler:       _EndpointApiV1_WatchEndpoints_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EndpointOperUpdate",
			Handler:       _EndpointApiV1_EndpointOperUpdate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "endpoint.proto",
}

func (m *Endpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Endpoint) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintEndpoint(dAtA, i, uint64(m.TypeMeta.Size()))
	n1, err := m.TypeMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintEndpoint(dAtA, i, uint64(m.ObjectMeta.Size()))
	n2, err := m.ObjectMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x1a
	i++
	i = encodeVarintEndpoint(dAtA, i, uint64(m.Spec.Size()))
	n3, err := m.Spec.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	dAtA[i] = 0x22
	i++
	i = encodeVarintEndpoint(dAtA, i, uint64(m.Status.Size()))
	n4, err := m.Status.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	return i, nil
}

func (m *EndpointSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndpointSpec) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.VrfName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.VrfName)))
		i += copy(dAtA[i:], m.VrfName)
	}
	if len(m.NetworkName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.NetworkName)))
		i += copy(dAtA[i:], m.NetworkName)
	}
	if len(m.IPv4Addresses) > 0 {
		for _, s := range m.IPv4Addresses {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.IPv6Addresses) > 0 {
		for _, s := range m.IPv6Addresses {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.MacAddress) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.MacAddress)))
		i += copy(dAtA[i:], m.MacAddress)
	}
	if len(m.NodeUUID) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.NodeUUID)))
		i += copy(dAtA[i:], m.NodeUUID)
	}
	if len(m.HomingHostAddr) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.HomingHostAddr)))
		i += copy(dAtA[i:], m.HomingHostAddr)
	}
	if m.UsegVlan != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(m.UsegVlan))
	}
	if len(m.Migration) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.Migration)))
		i += copy(dAtA[i:], m.Migration)
	}
	if len(m.MirrorSessions) > 0 {
		for _, s := range m.MirrorSessions {
			dAtA[i] = 0x5a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *EndpointStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndpointStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.EnicID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(m.EnicID))
	}
	if len(m.NodeUUID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.NodeUUID)))
		i += copy(dAtA[i:], m.NodeUUID)
	}
	if len(m.Migration) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(len(m.Migration)))
		i += copy(dAtA[i:], m.Migration)
	}
	return i, nil
}

func (m *EndpointList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndpointList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Endpoints) > 0 {
		for _, msg := range m.Endpoints {
			dAtA[i] = 0xa
			i++
			i = encodeVarintEndpoint(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *EndpointEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndpointEvent) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.EventType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintEndpoint(dAtA, i, uint64(m.EventType))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintEndpoint(dAtA, i, uint64(m.Endpoint.Size()))
	n5, err := m.Endpoint.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	return i, nil
}

func (m *EndpointEventList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EndpointEventList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.EndpointEvents) > 0 {
		for _, msg := range m.EndpointEvents {
			dAtA[i] = 0xa
			i++
			i = encodeVarintEndpoint(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintEndpoint(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Endpoint) Size() (n int) {
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovEndpoint(uint64(l))
	l = m.ObjectMeta.Size()
	n += 1 + l + sovEndpoint(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovEndpoint(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovEndpoint(uint64(l))
	return n
}

func (m *EndpointSpec) Size() (n int) {
	var l int
	_ = l
	l = len(m.VrfName)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	l = len(m.NetworkName)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	if len(m.IPv4Addresses) > 0 {
		for _, s := range m.IPv4Addresses {
			l = len(s)
			n += 1 + l + sovEndpoint(uint64(l))
		}
	}
	if len(m.IPv6Addresses) > 0 {
		for _, s := range m.IPv6Addresses {
			l = len(s)
			n += 1 + l + sovEndpoint(uint64(l))
		}
	}
	l = len(m.MacAddress)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	l = len(m.NodeUUID)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	l = len(m.HomingHostAddr)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	if m.UsegVlan != 0 {
		n += 1 + sovEndpoint(uint64(m.UsegVlan))
	}
	l = len(m.Migration)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	if len(m.MirrorSessions) > 0 {
		for _, s := range m.MirrorSessions {
			l = len(s)
			n += 1 + l + sovEndpoint(uint64(l))
		}
	}
	return n
}

func (m *EndpointStatus) Size() (n int) {
	var l int
	_ = l
	if m.EnicID != 0 {
		n += 1 + sovEndpoint(uint64(m.EnicID))
	}
	l = len(m.NodeUUID)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	l = len(m.Migration)
	if l > 0 {
		n += 1 + l + sovEndpoint(uint64(l))
	}
	return n
}

func (m *EndpointList) Size() (n int) {
	var l int
	_ = l
	if len(m.Endpoints) > 0 {
		for _, e := range m.Endpoints {
			l = e.Size()
			n += 1 + l + sovEndpoint(uint64(l))
		}
	}
	return n
}

func (m *EndpointEvent) Size() (n int) {
	var l int
	_ = l
	if m.EventType != 0 {
		n += 1 + sovEndpoint(uint64(m.EventType))
	}
	l = m.Endpoint.Size()
	n += 1 + l + sovEndpoint(uint64(l))
	return n
}

func (m *EndpointEventList) Size() (n int) {
	var l int
	_ = l
	if len(m.EndpointEvents) > 0 {
		for _, e := range m.EndpointEvents {
			l = e.Size()
			n += 1 + l + sovEndpoint(uint64(l))
		}
	}
	return n
}

func sovEndpoint(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEndpoint(x uint64) (n int) {
	return sovEndpoint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Endpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Endpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Endpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEndpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndpointSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndpointSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndpointSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IPv4Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IPv4Addresses = append(m.IPv4Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IPv6Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IPv6Addresses = append(m.IPv6Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MacAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MacAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HomingHostAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HomingHostAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsegVlan", wireType)
			}
			m.UsegVlan = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UsegVlan |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Migration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Migration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MirrorSessions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MirrorSessions = append(m.MirrorSessions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEndpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndpointStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndpointStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndpointStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnicID", wireType)
			}
			m.EnicID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnicID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Migration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Migration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEndpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndpointList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndpointList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndpointList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endpoints = append(m.Endpoints, &Endpoint{})
			if err := m.Endpoints[len(m.Endpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEndpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndpointEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndpointEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndpointEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventType", wireType)
			}
			m.EventType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventType |= (api.EventType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Endpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEndpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EndpointEventList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EndpointEventList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EndpointEventList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEndpoint
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointEvents = append(m.EndpointEvents, &EndpointEvent{})
			if err := m.EndpointEvents[len(m.EndpointEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEndpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEndpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEndpoint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEndpoint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEndpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEndpoint
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEndpoint
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEndpoint(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEndpoint = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEndpoint   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("endpoint.proto", fileDescriptorEndpoint) }

var fileDescriptorEndpoint = []byte{
	// 986 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4f, 0x6f, 0xdb, 0xb6,
	0x1b, 0x8e, 0x6c, 0x37, 0xb1, 0x99, 0xc6, 0x3f, 0x87, 0xf9, 0x25, 0x55, 0xdc, 0x36, 0xca, 0x0c,
	0x0c, 0x30, 0x8a, 0xca, 0x4e, 0xd3, 0xa2, 0x40, 0x81, 0xfd, 0x49, 0x84, 0xb8, 0x48, 0xba, 0xd9,
	0xce, 0x6c, 0x27, 0x3b, 0x06, 0x8a, 0xc4, 0x28, 0xdc, 0x2c, 0x92, 0x10, 0x69, 0x17, 0xd9, 0xd0,
	0x5d, 0xf6, 0x51, 0x76, 0xd8, 0x71, 0xc0, 0x3e, 0x45, 0x8e, 0xfd, 0x02, 0x13, 0x86, 0x1c, 0xf5,
	0x01, 0x76, 0x1e, 0x48, 0x4b, 0x91, 0xec, 0x38, 0xd8, 0x76, 0x23, 0xdf, 0xf7, 0x79, 0x9e, 0xf7,
	0x0f, 0xc9, 0x97, 0xa0, 0x8c, 0x88, 0xcb, 0x28, 0x26, 0xa2, 0xc1, 0x02, 0x2a, 0x28, 0x2c, 0x12,
	0x24, 0xd4, 0xaa, 0xfa, 0xc4, 0xa3, 0xd4, 0x1b, 0xa2, 0xa6, 0xcd, 0x70, 0xd3, 0x26, 0x84, 0x0a,
	0x5b, 0x60, 0x4a, 0xf8, 0x04, 0x57, 0x6d, 0x79, 0x58, 0x5c, 0x8e, 0xce, 0x1b, 0x0e, 0xf5, 0x9b,
	0x0c, 0x11, 0x6e, 0x13, 0x97, 0x36, 0xf9, 0xfb, 0xe6, 0x18, 0x11, 0xec, 0xa0, 0xe6, 0x48, 0xe0,
	0x21, 0x97, 0x54, 0x0f, 0x91, 0x2c, 0xbb, 0x89, 0x89, 0x33, 0x1c, 0xb9, 0x28, 0x91, 0x31, 0x33,
	0x32, 0x1e, 0xf5, 0x68, 0x53, 0x99, 0xcf, 0x47, 0x17, 0x6a, 0xa7, 0x36, 0x6a, 0x15, 0xc3, 0x3f,
	0xbd, 0x27, 0xaa, 0xcc, 0xd1, 0x47, 0xc2, 0x9e, 0xc0, 0x6a, 0xbf, 0xe6, 0x40, 0xb1, 0x15, 0xd7,
	0x05, 0xbf, 0x00, 0xc5, 0xc1, 0x15, 0x43, 0x6d, 0x24, 0x6c, 0x5d, 0xdb, 0xd6, 0xea, 0xcb, 0xbb,
	0x2b, 0x0d, 0x9b, 0xe1, 0x46, 0x62, 0xb4, 0xd6, 0xae, 0x43, 0x63, 0xe1, 0x63, 0x68, 0x68, 0x51,
	0x68, 0x2c, 0x3d, 0xc7, 0x64, 0x88, 0x09, 0xea, 0xdd, 0x72, 0xe0, 0x57, 0x00, 0x74, 0xcf, 0xbf,
	0x43, 0x8e, 0x50, 0x0a, 0x39, 0xa5, 0xf0, 0x3f, 0xa5, 0x90, 0x9a, 0xad, 0x6a, 0x46, 0xa3, 0x2c,
	0x33, 0x79, 0x4e, 0x7d, 0x2c, 0x90, 0xcf, 0xc4, 0x55, 0x2f, 0x43, 0x87, 0x16, 0x28, 0xf4, 0x19,
	0x72, 0xf4, 0xbc, 0x92, 0xd9, 0x68, 0x24, 0xdd, 0x6e, 0x24, 0xe9, 0x4a, 0xaf, 0xb5, 0x21, 0xd5,
	0xa4, 0x12, 0x67, 0xc8, 0xc9, 0x28, 0x29, 0x2e, 0x7c, 0x07, 0x16, 0xfb, 0xc2, 0x16, 0x23, 0xae,
	0x17, 0x94, 0x8a, 0x3e, 0x47, 0x45, 0xf9, 0x2d, 0x3d, 0xd6, 0xa9, 0x70, 0xb5, 0xcf, 0x28, 0xc5,
	0x0a, 0xb5, 0xbf, 0x0a, 0xe0, 0x61, 0x36, 0x34, 0xdc, 0x01, 0x4b, 0xa7, 0xc1, 0x45, 0xc7, 0xf6,
	0x91, 0x6a, 0x56, 0xc9, 0xda, 0x88, 0x42, 0x03, 0x8e, 0x83, 0x0b, 0x93, 0xd8, 0x3e, 0xca, 0x28,
	0x24, 0x30, 0xf8, 0x19, 0x58, 0xee, 0x20, 0xf1, 0x9e, 0x06, 0xdf, 0x2b, 0x56, 0x4e, 0xb1, 0xaa,
	0x51, 0x68, 0x6c, 0x90, 0x89, 0x79, 0x96, 0x99, 0x85, 0x43, 0x0b, 0xac, 0x1c, 0x1d, 0x8f, 0x5f,
	0xed, 0xbb, 0x6e, 0x80, 0x38, 0x47, 0x5c, 0xcf, 0x6f, 0xe7, 0xeb, 0x25, 0xeb, 0x49, 0x14, 0x1a,
	0x3a, 0x66, 0xe3, 0x57, 0xa6, 0x9d, 0x78, 0x32, 0x0a, 0xd3, 0x14, 0xb8, 0xa7, 0x34, 0x5e, 0xa7,
	0x1a, 0x05, 0xa5, 0xa1, 0x72, 0xc0, 0x6c, 0xfc, 0x3a, 0xd1, 0x98, 0x51, 0x48, 0x09, 0xf0, 0x0d,
	0x00, 0x6d, 0xdb, 0x89, 0xf7, 0xfa, 0x03, 0x55, 0xc2, 0x66, 0x14, 0x1a, 0xeb, 0xbe, 0xed, 0xcc,
	0x61, 0x67, 0xc0, 0xf0, 0x25, 0x28, 0x76, 0xa8, 0x8b, 0x4e, 0x4e, 0x8e, 0x0e, 0xf4, 0x45, 0x45,
	0x7c, 0x14, 0x85, 0xc6, 0x1a, 0xa1, 0x2e, 0x32, 0x47, 0x23, 0xec, 0x66, 0x68, 0xb7, 0x40, 0x78,
	0x04, 0xca, 0x87, 0xd4, 0xc7, 0xc4, 0x3b, 0xa4, 0x5c, 0x48, 0x25, 0x7d, 0x49, 0x51, 0x3f, 0x89,
	0x42, 0xe3, 0xe9, 0xa5, 0xf2, 0x98, 0x97, 0x94, 0x8b, 0x39, 0xb1, 0x67, 0x88, 0x32, 0xfe, 0x09,
	0x47, 0xde, 0xe9, 0xd0, 0x26, 0x7a, 0x71, 0x5b, 0xab, 0xaf, 0x4c, 0xe2, 0x8f, 0x38, 0xf2, 0xcc,
	0xf1, 0xd0, 0x26, 0xd9, 0xf8, 0x09, 0x10, 0xbe, 0x01, 0xa5, 0x36, 0xf6, 0x02, 0xf5, 0x26, 0xf5,
	0x92, 0x0a, 0xfd, 0xf8, 0x7a, 0x72, 0x7b, 0xd7, 0xfc, 0xc4, 0x91, 0x61, 0xa6, 0x68, 0xd8, 0x02,
	0xe5, 0x36, 0x0e, 0x02, 0x1a, 0xf4, 0x11, 0xe7, 0xf2, 0x49, 0xeb, 0xcb, 0xaa, 0xdb, 0x4f, 0xa3,
	0xd0, 0xd8, 0xf4, 0x95, 0xc7, 0xe4, 0xb1, 0x2b, 0x56, 0x10, 0xec, 0xaa, 0x37, 0x43, 0xaa, 0xfd,
	0xa6, 0x81, 0xf2, 0xf4, 0x6d, 0x85, 0x26, 0x58, 0x6c, 0x11, 0xec, 0x1c, 0x1d, 0xa8, 0x9b, 0x57,
	0xb0, 0xd6, 0xa3, 0xd0, 0x58, 0x95, 0xe3, 0xc4, 0x9c, 0xea, 0x62, 0x0c, 0x9a, 0x6a, 0x7c, 0xee,
	0xdf, 0x36, 0x7e, 0xaa, 0xf0, 0xfc, 0x7f, 0x29, 0xbc, 0xb6, 0x97, 0xbe, 0x94, 0xaf, 0x31, 0x17,
	0x70, 0x07, 0x94, 0x92, 0xd9, 0xc9, 0x75, 0x6d, 0x3b, 0x5f, 0x5f, 0xde, 0x85, 0x77, 0x5f, 0x62,
	0x2f, 0x05, 0xd5, 0x7e, 0xd1, 0xc0, 0x4a, 0x62, 0x6f, 0x8d, 0x11, 0x11, 0xf0, 0x2d, 0x28, 0xa9,
	0x85, 0x1c, 0x36, 0xaa, 0xea, 0xf2, 0x6e, 0x59, 0x8d, 0x96, 0x5b, 0xab, 0xa5, 0x47, 0xa1, 0xf1,
	0x7f, 0x24, 0xb7, 0xa6, 0xb8, 0x62, 0xd9, 0x77, 0x94, 0x52, 0xe1, 0xbb, 0x74, 0xde, 0xc5, 0x13,
	0x6a, 0x4e, 0x2a, 0x93, 0x21, 0x25, 0x9f, 0x73, 0x92, 0x52, 0xb6, 0x45, 0x09, 0xaa, 0x36, 0x00,
	0xab, 0x53, 0x49, 0xaa, 0x62, 0xbf, 0x4c, 0x4f, 0x4b, 0x19, 0x93, 0x8a, 0x1f, 0xdd, 0x0d, 0xa3,
	0xfc, 0xbd, 0x19, 0xf8, 0xb3, 0x6f, 0xe4, 0xb5, 0x89, 0x5b, 0x29, 0xcf, 0x1b, 0xc1, 0x22, 0x28,
	0x74, 0xba, 0x9d, 0x56, 0x65, 0x01, 0x96, 0xc0, 0x83, 0xfe, 0x60, 0xbf, 0x37, 0xa8, 0x68, 0xd2,
	0x78, 0x20, 0x8d, 0x39, 0x69, 0xdc, 0xb7, 0xba, 0xbd, 0x41, 0x25, 0x0f, 0xd7, 0xc1, 0xea, 0xdb,
	0x5e, 0xb7, 0x7d, 0xd6, 0xe9, 0x76, 0xce, 0x8e, 0x5b, 0x9d, 0xb3, 0xc3, 0x6e, 0x7f, 0x50, 0x29,
	0xec, 0xfe, 0x91, 0x4b, 0xdb, 0xb9, 0xcf, 0xf0, 0xe9, 0x0b, 0x39, 0x08, 0x64, 0xb6, 0x89, 0x91,
	0xc3, 0x75, 0xd5, 0x4c, 0x69, 0xfb, 0xd6, 0x16, 0xce, 0x65, 0x97, 0xa9, 0x4f, 0xa8, 0x3a, 0x67,
	0xee, 0x4a, 0x4c, 0x6d, 0x01, 0x1e, 0x82, 0xb2, 0x42, 0xfe, 0xa3, 0xc4, 0xe3, 0x7b, 0x0a, 0x9f,
	0xe8, 0xec, 0x68, 0x70, 0x0f, 0xc0, 0xc4, 0xd1, 0x65, 0x28, 0x38, 0x61, 0xae, 0x2c, 0xfa, 0xbe,
	0x7e, 0x55, 0xa7, 0xff, 0xa4, 0xda, 0x42, 0x5d, 0xab, 0xfe, 0xf4, 0xfb, 0xcf, 0x9b, 0x3f, 0x64,
	0x3e, 0xb2, 0xc2, 0x50, 0x9e, 0x44, 0xde, 0x43, 0x02, 0x16, 0x18, 0x95, 0x4b, 0x36, 0x12, 0x70,
	0xd1, 0x45, 0x43, 0x24, 0x50, 0xf5, 0xf3, 0xe6, 0x8f, 0xe9, 0x3f, 0xd3, 0x18, 0x20, 0x62, 0x13,
	0xf1, 0x61, 0xca, 0x26, 0xe7, 0x2d, 0x67, 0xb6, 0x83, 0xee, 0x9a, 0x3f, 0xd4, 0x56, 0xe4, 0x17,
	0x7a, 0x7b, 0x55, 0x9f, 0xe5, 0x4e, 0x5f, 0x58, 0x0f, 0xaf, 0x6f, 0xb6, 0xb4, 0x8f, 0x37, 0x5b,
	0xda, 0x9f, 0x37, 0x5b, 0xda, 0xb1, 0x76, 0xbe, 0xa8, 0xf2, 0x7e, 0xf9, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x79, 0xf9, 0x7b, 0xc0, 0x33, 0x08, 0x00, 0x00,
}
