---
version: 2.0
targets:
  apollo/gtest:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/aarch64build:
    commands: ["make", "PIPELINE=apollo", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:avinash@pensando.io"]
    area:
    sub-area:
    feature:

  apollo/dol/oci/networking:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/oci/networking"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/dol/msft/networking:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/msft/networking"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/dol/lpm:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/lpm"]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/scale_test_mock:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/scale_test_mock"]
    owners: ["email:saratk@pensando.io", "email:vijasrin@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  #apollo/agent/testapp:
    #commands: ["make", "PIPELINE=apollo", "jobd/apollo/agent/testapp"]
    #owners: ["email:saratk@pensando.io", "email:vijasrin@pensando.io" ]
    #area:
    #sub-area:
    #feature:

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /usr/src/github.com/pensand/sw/nic/nic_sanity_logs.tar.gz
