---
version: 2.0
targets:
  apollo/gtest:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:

  apollo/aarch64build:
    commands: ["make", "PIPELINE=apollo", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:avinash@pensando.io"]
    area:
    sub-area:
    feature:

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /sw/nic/nic_apollo_sanity_logs.tar.gz
