---
version: 2.0
targets:
  apollo/gtest:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/aarch64build:
    commands: ["make", "PIPELINE=apollo", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:avinash@pensando.io"]
    area:
    sub-area:
    feature:

  apollo/dol/mplsoudp:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/mplsoudp"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/dol/vxlan:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/vxlan"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/dol/lpm:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/lpm"]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/dol/rfc:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/rfc"]
    owners: ["email:sai@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/dol/mirror:
    commands: ["make", "PIPELINE=apollo", "jobd/dol/apollo/mirror"]
    owners: ["email:vgunta@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/scale_test_mock:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/scale_test_mock"]
    owners: ["email:saratk@pensando.io", "email:vijasrin@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/aarch64_container:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/aarch64/container"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/x86_64_container:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/x86_64/container"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  apollo/valgrind:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/gtests-valgrind"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86

  #apollo/agent/testapp:
    #commands: ["make", "PIPELINE=apollo", "jobd/apollo/agent/testapp"]
    #owners: ["email:saratk@pensando.io", "email:vijasrin@pensando.io" ]
    #area:
    #sub-area:
    #feature:

  artemis/aarch64_build:
    commands: ["make", "PIPELINE=artemis", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:srikanth@pensando.io"]
    area:
    sub-area:
    feature:

  artemis/x86_build:
    commands: ["make", "PIPELINE=artemis"]
    owners: ["email:saratk@pensando.io","email:srikanth@pensando.io"]
    area:
    sub-area:
    feature:

  artemis/scale_test_mock:
    commands: ["make", "PIPELINE=artemis", "jobd/artemis/scale_test_mock"]
    owners: ["email:saratk@pensando.io", "email:vijasrin@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /usr/src/github.com/pensando/sw/nic/nic_sanity_logs.tar.gz
