---
version: 2.0
targets:
  sdk/make:
    commands: ["make", "jobd/make/sdk"]
    owners: ["email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/sdk/sdk_sanity_logs.tar.gz
