---
version: 2.0
targets:
  main:
    commands: ["sh", "-c", "cd /sdk && make lib && make test" ]
    owners: ["email:ksmurty@pensando.io"]
    area:
    sub-area:
    feature:
cache:
  name: "sdk"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sdk"
  work_dir: "/sdk"
rebase: true
logfiles:
