---
version: 2.0
builds:
  build-iris-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_iris_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_iris_x86.tar.gz
  build-iris-arm:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw && ls -al && make ws-tools && go install ./asset-build/... && make pull-assets && make naples-firmware && make naples-firmware-tarball"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/naples_fw_all.tgz
  build-iota:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw && ls -al && make ws-tools && go install ./asset-build/... && make pull-assets && cd iota && make iota-tarball"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/iota.tgz
  build-apollo-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=apollo package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_apollo_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_apollo_x86.tar.gz
  build-gft-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=gft package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_gft_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_gft_x86.tar.gz
  build-artemis-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=artemis package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_artemis_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_artemis_x86.tar.gz
  build-apulu-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=apulu package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_apulu_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_apulu_x86.tar.gz
  build-apulu-arm:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw && ls -al && make ws-tools && go install ./asset-build/... && make pull-assets && make PIPELINE=apulu PLATFORM=hw ARCH=aarch64 firmware"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/nic/naples_fw_.tar
  build-venice-image:
    commands: ["bash", "-c", "mkdir -p /sw/bin; cd /usr/src/github.com/pensando/sw/test/ci_targets/e2e-venice-image; GIT_VERSION=$(git describe --dirty --always) GIT_COMMIT=$(git rev-list -1 HEAD --abbrev-commit) go run make-venice-image.go"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/bin/venice.tgz
    repo_dir: "/import/src/github.com/pensando/sw"
    create:
      image: build-150
      count: 1
      resources:
        cpus: 16
        memory: 32
    provision:
      username: vm
      password: vm
      # additional vars to pass to ansible.
      vars:

targets:
  submodules:
    commands: ["sh", "-c", "TOP=/sw ./scripts/check-submodules.sh"]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/sw"
  work_dir: "/sw"
queue_name: builder
jobs:
  api:
    labels: ["2xhourly"]
  asset-build:
    labels: ["hourly"]
  docs:
    labels: ["hourly"]
  dol:
    labels: ["hourly"]
  iota:
    labels: ["hourly"]
  iota/test/venice:
    labels: ["2xhourly"]
  iota/test/standalone/sanity/freebsd:
    labels: ["precommit", "hourly"]
  iota/test/standalone/sanity/esx:
    labels: ["precommit", "hourly"]
  iota/test/standalone/regression/esx:
    labels: ["daily"]
  iota/test/standalone/regression/freebsd:
    labels: ["daily"]
  iota/test/standalone/regression/linux:
    labels: ["daily"]
  iota/test/standalone/sanity/linux:
    labels: ["precommit", "hourly"]
#  iota/test/venice/regression:
#    labels: ["daily"]
  iota/test/venice/sim:
    labels: ["hourly"]
  nic:
    labels: ["hourly"]
  nic/agent:
    labels: ["hourly"]
  nic/apollo:
    labels: ["hourly"]
  nic/sdk:
    labels: ["hourly"]
  nic/utils/ftlite:
    labels: ["hourly"]
  penctl:
    labels: ["hourly"]
  platform:
    labels: ["hourly"]
  platform/drivers/linux:
    labels: ["hourly"]
  platform/src/app/pciemgrd:
    labels: ["hourly"]
  storage/offload:
    labels: ["hourly"]
  storage/offload/linux-build-test:
    labels: ["hourly"]
  test:
    labels: ["hourly"]
  test/ci_targets/e2e:
    labels: ["2xhourly"]
  venice:
    labels: ["hourly"]
  venice/ui:
    labels: ["hourly"]

dependencies:
  api:
    - reference: test/ci_targets/e2e
    - reference: venice/ui
  dol/apollo:
    - reference: nic/apollo
  dol/artemis:
    - reference: nic/apollo
  dol/test/networking:
    - reference: nic
  events:
    - reference: venice/ui
  iota:
    - reference: iota/test/venice
      exclude_dirs: ["harness", "test/iris", "test/apollo"]
    - reference: iota/test/standalone/sanity/freebsd
      exclude_dirs: ["test/venice", "test/apollo"]
    - reference: iota/test/standalone/sanity/esx
      exclude_dirs: ["test/venice", "test/apollo"]
    - reference: iota/test/standalone/sanity/linux
      exclude_dirs: ["test/venice", "test/apollo"]
  metrics:
    - reference: venice/ui
  #nic/apollo:
  #  - reference: iota/test/venice
  #  - reference: iota/test/standalone/sanity/esx
  #  - reference: iota/test/standalone/sanity/freebsd
  #  - reference: iota/test/standalone/sanity/linux
  nic/agent:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: api
    - reference: test/ci_targets/e2e
  nic/asm:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/buildroot:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/conf:
    - reference: iota/test/standalone/sanity/linux
  nic/debug_cli:
    - reference: iota/test/standalone/sanity/linux
  nic/delphi:
    - reference: iota/test/standalone/sanity/linux
  nic/fte:
    - reference: iota/test/standalone/sanity/linux
  nic/hal:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/include:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/linkmgr:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/p4-hlir:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/p4:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/proto:
    - reference: iota/test/standalone/sanity/esx
  nic/sdk:
    - reference: iota/test/standalone/sanity/linux
    - reference: nic/apollo
  nic/sysmgr:
    - reference: iota/test/standalone/sanity/linux
  nic/third-party:
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  nic/tools:
    - reference: iota/test/standalone/sanity/linux
  nic/upgrade_manager:
    - reference: iota/test/standalone/sanity/esx
  nic/utils:
    - reference: iota/test/standalone/sanity/linux
  nic/conf/apollo:
    - reference: nic/apollo
  nic/conf/artemis:
    - reference: nic/apollo
  nic/debug_cli/apollo:
    - reference: nic/apollo
  nic/sdk/platform/cfgspace:
    - reference: platform/src/app/pciemgrd
  nic/sdk/platform/pciehdevices:
    - reference: platform/src/app/pciemgrd
  nic/sdk/platform/pciemgr:
    - reference: platform/src/app/pciemgrd
  nic/sdk/platform/pciemgrd:
    - reference: platform/src/app/pciemgrd
  platform/drivers:
    - reference: iota/test/standalone/sanity/esx
      exclude_dirs: ["freebsd","linux"]
    - reference: iota/test/standalone/sanity/freebsd
      exclude_dirs: ["linux","esx"]
    - reference: iota/test/standalone/sanity/linux
      exclude_dirs: ["freebsd","esx"]
  platform/src/app/asicerrord:
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/captrace:
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/cpld:
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/diag:
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/fructl:
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/nicmgrd:
    - reference: nic/apollo
    - reference: iota/test/venice
    - reference: iota/test/standalone/sanity/esx
    - reference: iota/test/standalone/sanity/freebsd
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/pciemgrd:
    - reference: iota/test/standalone/sanity/linux
    - reference: nic/apollo
  platform/src/app/pcieutil/src:
    - reference: iota/test/standalone/sanity/linux
  platform/src/app/sysmond:
    - reference: iota/test/standalone/sanity/linux
 # platform:
 #   - reference: nic/apollo
 #     exclude_dirs: ["doc", "drivers"]
 #   - reference: iota/test/venice
 #     exclude_dirs: ["doc", "drivers/linux", "drivers/freebsd"]
 #   - reference: iota/test/standalone/sanity/esx
 #     exclude_dirs: ["doc", "drivers/linux", "drivers/freebsd"]
 #   - reference: iota/test/standalone/sanity/freebsd
 #     exclude_dirs: ["doc", "drivers/linux", "drivers/esxi"]
 #   - reference: iota/test/standalone/sanity/linux
 #     exclude_dirs: ["doc", "drivers/freebsd", "drivers/esxi"]
  platform/src/third-party/app/pciutils:
    - reference: platform/src/app/pciemgrd
  storage/offload:
    - reference: storage/offload/linux-build-test
  venice:
    - reference: api
    - reference: test/ci_targets/e2e
    - reference: iota/test/venice
      exclude_dirs: ["ui"]
  test:
    - reference: api
    - reference: test/ci_targets/e2e
    - reference: platform
  vendor:
    - reference: api
    - reference: venice
    - reference: test/ci_targets/e2e