---
targets:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
rebase: true
references:
  - nic
  - nic/sim/warmd
  - dol
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
#Disabling as failing on top
#  - test/suites/e2esanities
  - test/ci_targets/e2e
#  - test/ci_targets/e2etelemetry
  - storage/offload
dependencies:
  test: nic
  test: platform
  nic: platform
  dol: nic
  dol/test/networking : nic
  nic/agent: venice
  venice: test
  test: test/ci_targets/e2e
