---
version: 2.0
targets:
  submodules:
    commands: ["/go/src/github.com/pensando/sw/scripts/check-submodules.sh", ""]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
rebase: true
references:
  - nic
  - nic/apollo
  - dol
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
#Disabling as failing on top
#  - test/suites/e2esanities
  - test/ci_targets/e2e
#  - test/venice_naples_e2e
#  - test/ci_targets/e2etelemetry
  - storage/offload
  - iota
  - iota/test/venice
dependencies:
  test: nic
  test: platform
  nic: platform
#  nic: test/venice_naples_e2e
  platform: nic
#  platform: test/venice_naples_e2e
#  venice: test/venice_naples_e2e
#  iota: test/venice_naples_e2e
  dol: nic
  dol/test/networking : nic
  nic/agent: venice
  nic/agent: test/ci_targets/e2e
  venice: test
  venice: test/ci_targets/e2e
  test: test/ci_targets/e2e
