---
version: 2.0
builds:
  build-iris-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_iris_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_iris_x86.tar.gz
  build-apollo-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=apollo package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_apollo_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_apollo_x86.tar.gz
  build-gft-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=gft package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_gft_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_gft_x86.tar.gz
  build-venice-image:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make venice-image"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/bin/venice.tgz
targets:
  submodules:
    commands: ["sh", "-c", "TOP=/sw ./scripts/check-submodules.sh"]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/sw"
  work_dir: "/sw"
references:
  - nic
  - penctl
  - nic/apollo
  - nic/sdk
  - dol
  - dol/apollo
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
#Disabling as failing on top
#  - test/suites/e2esanities
  - test/ci_targets/e2e
#  - test/ci_targets/e2etelemetry
  - storage/offload
  - iota
  - iota/test/venice
  - platform/drivers/linux
  - iota/test/venice/hwtest
  - iota/test/venice/hwtest/hwregression

dependencies:
  #test: nic
  test: platform
  #  nic: platform
  nic: iota/test/venice/hwtest
  #platform: nic
  platform: iota/test/venice/hwtest
  venice: iota/test/venice/hwtest
  iota: iota/test/venice/hwtest
  #dol: nic
  dol: iota/test/venice/hwtest 
  dol/test/networking : nic
  #nic/agent: venice
  nic/agent: test/ci_targets/e2e
  #venice: test
  venice: test/ci_targets/e2e
  #test: test/ci_targets/e2e
  nic/apollo: nic
  dol/apollo: nic/apollo
