---
targets:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
rebase: true
references:
  - nic
  - dol
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
#Disabling as failing on top
#  - test/suites/e2esanities
  - test/ci_targets/e2e
#  - test/ci_targets/e2etelemetry
  - storage/offload
  - iota
dependencies:
  test: nic
  test: platform
  nic: platform
  platform: nic
  dol: nic
  dol/test/networking : nic
  nic/agent: venice
  nic/agent: test/ci_targets/e2e
  venice: test
  venice: test/ci_targets/e2e
  test: test/ci_targets/e2e
  iota: nic
