---
targets:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
rebase: true
references:
  - nic
  - dol
  - dol/test/networking
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
  - test/suites/e2e
  - test/suites/e2esanities
  - storage/offload
dependencies:
  dol: nic
  dol/test/networking : nic
  nic/agent: venice
  venice: test
