---
version: 2.0
builds:
  build-iris-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_iris_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_iris_x86.tar.gz
  build-iris-arm:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw && ls -al && make ws-tools && go install ./asset-build/... && make pull-assets && make naples-firmware && make naples-firmware-tarball"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/naples_fw_all.tgz
  build-iota:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw && ls -al && make ws-tools && go install ./asset-build/... && make pull-assets && cd iota && make iota-tarball"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/iota.tgz
  build-apollo-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=apollo package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_apollo_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_apollo_x86.tar.gz
  build-gft-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=gft package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_gft_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_gft_x86.tar.gz
  build-artemis-x86:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && go install ./asset-build/... && make pull-assets && cd nic && make PIPELINE=artemis package && find ./build -name '*.o'  | xargs rm && tar -zvcf /sw/build_artemis_x86.tar.gz /usr/src/github.com/pensando/sw/nic/build"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/build_artemis_x86.tar.gz
  build-venice-image:
    commands: ["bash", "-c", "mkdir -p /sw/bin; cd /usr/src/github.com/pensando/sw/test/ci_targets/e2e-venice-image; GIT_VERSION=$(git describe --dirty --always) GIT_COMMIT=$(git rev-list -1 HEAD --abbrev-commit) go run make-venice-image.go"]
    owners: ["email:sw-team@pensando.io"]
    artifacts:
      - /sw/bin/venice.tgz
    repo_dir: "/import/src/github.com/pensando/sw"
    create:
      image: build-150
      count: 1
      resources:
        cpus: 16
        memory: 32
    provision:
      username: vm
      password: vm
      # additional vars to pass to ansible.
      vars:

targets:
  submodules:
    commands: ["sh", "-c", "TOP=/sw ./scripts/check-submodules.sh"]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/sw"
  work_dir: "/sw"
queue_name: builder
references:
  - nic
  - penctl
  - nic/apollo
  - nic/sdk
  - dol
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
#Disabling as failing on top
#  - test/suites/e2esanities
  - test/ci_targets/e2e
# - test/ci_targets/e2erollout
#  - test/ci_targets/e2etelemetry
  - storage/offload
  - storage/offload/linux-build-test
  - iota
  - iota/test/venice
  - iota/test/no-venice
  - platform/drivers/linux
  - iota/test/venice/hwtest
  - iota/test/venice/hwtest/hwregression
  - nic/utils/ftlite
  - nic/apollo/doc

dependencies:
  platform:
    - reference: nic/apollo
    - reference: iota/test/venice/hwtest
      exclude_dirs: ["doc", "drivers/linux", "drivers/freebsd"]
    - reference: iota/test/venice/no-venice
      exclude_dirs: ["doc"]
  vendor:
    - reference: api
    - reference: venice
    - reference: test/ci_targets/e2e
  nic:
    - reference: iota/test/venice/hwtest
      exclude_dirs: ["apollo", "doc"]
    - reference: iota/test/no-venice
      exclude_dirs: ["apollo", "doc"]
  nic/agent:
    - reference: api
    - reference: test/ci_targets/e2e
  nic/apollo:
    - reference: nic/apollo/doc
  nic/sdk:
    - reference: nic/apollo
  nic/conf/apollo:
    - reference: nic/apollo
  nic/conf/artemis:
    - reference: nic/apollo
  dol/apollo:
    - reference: nic/apollo
  dol/artemis:
    - reference: nic/apollo
  dol/test/networking: 
    - reference: nic
  nic/debug_cli/apollo:
    - reference: nic/apollo
  venice:
    - reference: api
    - reference: test/ci_targets/e2e
    - reference: iota/test/venice/hwtest
  test:
    - reference: api
    - reference: test/ci_targets/e2e
    - reference: platform
  api:
    - reference: test/ci_targets/e2e
    - reference: venice/ui
  metrics:
    - reference: venice/ui
  events:
    - reference: venice/ui
  iota:
    - reference: iota/test/venice/hwtest
    - reference: iota/test/venice/no-venice
  storage/offload: 
    - reference: storage/offload/linux-build-test
