---
targets:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
rebase: true
references:
  - nic
  - dol
  - venice
  - api
  - platform
  - nic/agent
  - test
  - docs
  - venice/ui
dependencies:
  dol: nic
  nic/agent: venice
  venice: test
