---
version: 2.0
targets:
  checks:
    commands: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && make checks ; exit $ret" ]
    owners: ["email:arathore@pensando.io"]
    area:
    sub-area:
    feature:

  linux:
    commands: ["sh", "-c", "make -C $GOPATH/src/github.com/pensando/sw/nic/upgrade_manager/export/upggosdk && cd $GOPATH/src/github.com/pensando/sw/penctl && make && file ../nic/build/x86_64/iris/bin/penctl.linux | grep statically | grep linked | grep not | grep stripped ; exit $ret" ]
    owners: ["email:arathore@pensando.io"]
    area:
    sub-area:
    feature:

  freebsd:
    commands: ["sh", "-c", "make -C $GOPATH/src/github.com/pensando/sw/nic/upgrade_manager/export/upggosdk && cd $GOPATH/src/github.com/pensando/sw/penctl && make && file ../nic/build/x86_64/iris/bin/penctl.freebsd | grep statically | grep linked | grep not | grep stripped ; exit $ret" ]
    owners: ["email:arathore@pensando.io"]
    area:
    sub-area:
    feature:

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
  - /sw/iota/iota_sanity_logs.tar.gz

