---
targets:
  main: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && make bazel-gtests && make run-gtests" ]
  def:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --storage" ]
  fte:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte" ]
  norm: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo norm --feature norm" ]
  eth:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo eth --feature eth" ]
  acl:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo acl --feature acl" ]
  proxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature proxy" ]
  ipsec:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature ipsec" ]
  networking:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo up2up --feature networking" ]
  vxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo vxlan --feature vxlan" ]
  ipsg:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo eth --feature ipsg" ]
  firewall:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo firewall --feature firewall" ]
  admin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo admin --feature admin" ]
  hostpin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte --hostpin" ]
  agent: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && (./tools/start-hal-stub.sh &) && cd $GOPATH/src/github.com/pensando/sw && go test -v ./test/integ/venice_integ... -datapath=hal && go test -v ./test/integ/npminteg/..."]
  agent: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && go test ./test/integ/..."]
  l2mc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo mcast --feature l2mc" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  name: "pensando/nic"
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
