---
targets:
  main: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && make bazel-gtests && make run-gtests" ]
  storage:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --storage" ]
  rdma:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo rdma --feature rdma,rdma_perf" ]
  config:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --configtest" ]
  fte:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte" ]
  fte2:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte2" ]
  ftevxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature ftevxlan" ]
  norm: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo norm --feature norm" ]
  eth:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo eth --feature eth" ]
  acl:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo acl --feature acl" ]
  proxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature proxy" ]
  e2etlsproxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature proxy --config-only --e2e-tls-dol" ]
  ipsec:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature ipsec" ]
  networking:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo up2up --feature networking" ]
  vxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo vxlan --feature vxlan" ]
  ipsg:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo eth --feature ipsg" ]
  firewall:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo firewall --feature firewall" ]
  admin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo admin --feature admin" ]
  pin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte,hostpin --hostpin" ]
  pin2:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte2 --hostpin" ]
  pinvxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature ftevxlan,hpvxlan --hostpin" ]
  agent: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && (./tools/start-hal-stub.sh &) && cd $GOPATH/src/github.com/pensando/sw && go test -v ./test/integ/venice_integ... -datapath=hal -agents=1 && go test -v ./test/integ/npminteg/..."]
  multicast:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo multicast --feature multicast" ]
  pinl2mc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo multicast --feature pinl2mc --hostpin" ]
  l4lb:  ["sh", "-c", "make l4lb"]
  recirc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo recirc --feature recirc" ]
  classic:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo classic --feature classic --classic" ]
  parser:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo parser --feature parser" ]
  telemetry:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo telemetry --feature telemetry" ]
  app_redir:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature app_redir" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  name: "pensando/nic"
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /sw/dol/dol.log
  - /sw/nic/hal.log
  - /sw/nic/model.log
  - /sw/nic/build.log
  - /sw/nic/storage_dol.log
