---
targets:
  main: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make bazel-build && make bazel-gtests && make clean" ]
  # Commented out tests for PD Cleanup.
  #main: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make bazel-build && make bazel-gtests && make run-gtests && make clean" ]
  #arm_build: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make capsim-master && make ARCH=aarch64 bazel-build && make ARCH=aarch64 bazel-gtests && make clean" ]
  storage:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --storage" ]
  # config:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --configtest" ]
  rdma:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo rdma --feature rdma" ]
  rdma_ext:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo rdma --feature rdma_ext,rdma_perf" ]
  fte:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo fte --feature fte --lite" ]
  fte2:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo fte --feature fte2 --lite" ]
  ftevxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo fte --feature ftevxlan --lite" ]
  alg: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo alg --feature alg" ]
  norm: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo norm --feature norm" ]
  eth:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo eth --feature eth" ]
  acl:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo acl --feature acl" ]
  proxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo proxy --feature proxy" ]
  e2etlsproxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo proxy --feature proxy --config-only --e2e-tls-dol" ]
  ipsec:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo proxy --feature ipsec --no_error_check" ]
  networking:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo up2up --feature networking" ]
  vxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo vxlan --feature vxlan" ]
  ipsg:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo eth --feature ipsg" ]
  firewall:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo firewall --feature firewall" ]
  # admin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo admin --feature admin" ]
  pin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo fte --feature fte,hostpin --hostpin --lite" ]
  pin2:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo fte --feature fte2 --hostpin --lite" ]
  pinvxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo fte --feature ftevxlan,hpvxlan --hostpin --lite" ]
  agent: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make pull-assets && make checks && cd nic && make bazel-build && (./tools/start-hal-stub.sh &) && cd $GOPATH/src/github.com/pensando/sw && go test -v ./test/integ/venice_integ -run TestVeniceInteg -datapath=hal -agents=1 && go test -v ./test/integ/npminteg/..."]
  multicast:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo multicast --feature multicast" ]
  pinl2mc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo multicast --feature pinl2mc --hostpin" ]
  l4lb:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo l4lb --feature l4lb" ]
  dos:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo dos --feature dos" ]
  recirc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo recirc --feature recirc" ]
  classic:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo classic --feature classic --classic" ]
  classicl2mc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo classic --feature classicl2mc --classic" ]
  parser:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo parser --feature parser" ]
  telemetry:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo telemetry --feature telemetry" ]
  p4pt:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature p4pt" ]
  app_redir:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo app_redir --feature app_redir" ]
  e2el7:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo proxy --feature proxy --config-only --e2e-l7-dol" ]
  # configtoggle: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo up2up --feature networking --configtoggle" ]
  gft:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make gft && ./run.py  --gft" ]
  base:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py  --topo base --feature eth,networking,rdma_base --lite" ]
  proto-sync: ["sh", "-c", "cd /sw && make pull-assets && cd $GOPATH/src/github.com/pensando/sw/nic/agent/netagent/datapath/halproto && make proto-sync"]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /sw/dol/dol.log
  - /sw/nic/hal.log
  - /sw/nic/model.log
  - /sw/nic/build.log
  - /sw/nic/storage_dol.log
  - /sw/nic/tcp_client.log
  - /sw/nic/tcp_server.log
  - /sw/nic/tls_server.log
  - /sw/nic/hntap.log
  - /sw/nic/core.hal
  - /sw/nic/core.cap_model
  - /sw/nic/http_client.log
  - /sw/nic/http_server.log
