---
targets:
  main: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && make bazel-gtests && make run-gtests" ]
  def:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py" ]
  fte:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo fte --feature fte" ]
  norm: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo norm --feature norm" ]
  eth:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo eth --feature eth" ]
  acl:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo acl --feature acl" ]
  proxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo proxy --feature proxy" ]
  networking:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo up2up --feature networking" ]
  vxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo vxlan --feature vxlan" ]
  ipsg:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo eth --feature ipsg" ]
  firewall:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo up2up --feature firewall" ]
  admin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make bazel-build && ./run.py --topo admin --feature admin" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  name: "pensando/nic"
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
