---
version: 2.0
targets:
  platform/drivers:
    commands: ["make", "jobd/platform/drivers"]
    owners: ["email:dbarsky@pensando.io"]
    area:
    sub-area:
    feature:
  gtests:
    commands: ["make", "jobd/gtests"]
    owners: ["email:saratk@pensando.io"]
    area:
    sub-area:
    feature:
  halctl:
    commands: ["make", "jobd/halctl"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== ARM Tests ===========================
  arm/build:
    commands: ["make", "ARCH=aarch64"]
    owners: ["email:dbarsky@pensando.io"]
    area:
    sub-area:
    feature:
  arm/build/haps:
    commands: ["make", "ARCH=aarch64", "PLATFORM=haps", "package-haps-dbg"]
    owners: ["email:dbarsky@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== Storage Tests ===========================
  storage:
    commands: ["make", "jobd/storage"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:
  storage/perf:
    commands: ["make", "jobd/storage/perf"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:
  storage/nvme:
    commands: ["make", "jobd/storage/nvme"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:
  #storage/nvme_perf:
  # commands: ["make", "jobd/storage/nvme_perf"]
  # owners: ["email:piraman@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #storage/nicmgr:
  # commands: ["make", "jobd/storage/nicmgr"]
  # owners: ["email:piraman@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #Test running into locking issues - disabling for now
  #storage/combined:
  # commands: ["make", "jobd/storage/combined"]
  # owners: ["email:piraman@pensando.io"]
  # area:
  # sub-area:
  # feature:

  # ====================== Config Tests ===========================
  #configtest:
  # commands: ["make", "jobd/configtest"]
  # owners: ["email:dbarsky@pensando.io"]
  # area:
  # sub-area:
  # feature:

  # ====================== DOL Tests ===========================
  dol/rdma:
    commands: ["make", "jobd/dol/rdma"]
    owners: ["email:ksmurty@pensando.io"]
    area:
    sub-area:
    feature:
  dol/rdma_ext:
    commands: ["make", "jobd/dol/rdma_ext"]
    owners: ["email:ksmurty@pensando.io"]
    area:
    sub-area:
    feature:
  dol/fte:
    commands: ["make", "jobd/dol/fte"]
    owners: ["email:lseshan@pensando.io"]
    area:
    sub-area:
    feature:
  dol/fte2:
    commands: ["make", "jobd/dol/fte2"]
    owners: ["email:lseshan@pensando.io"]
    area:
    sub-area:
    feature:
  dol/ftevxlan:
    commands: ["make", "jobd/dol/ftevxlan"]
    owners: ["email:lseshan@pensando.io"]
    area:
    sub-area:
    feature:
  dol/alg:
    commands: ["make", "jobd/dol/alg"]
    owners: ["email:pavramas@pensando.io"]
    area:
    sub-area:
    feature:
  dol/norm:
    commands: ["make", "jobd/dol/norm"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/eth:
    commands: ["make", "jobd/dol/eth"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
  dol/acl:
    commands: ["make", "jobd/dol/acl"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/proxy:
    commands: ["make", "jobd/dol/proxy"]
    owners: ["email:raghava@pensando.io"]
    area:
    sub-area:
    feature:
  dol/ipsec:
    commands: ["make", "jobd/dol/ipsec"]
    owners: ["email:rameshp@pensando.io"]
    area:
    sub-area:
    feature:
  dol/networking:
    commands: ["make", "jobd/dol/networking"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/vxlan:
    commands: ["make", "jobd/dol/vxlan"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/ipsg:
    commands: ["make", "jobd/dol/ipsg"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/firewall:
    commands: ["make", "jobd/dol/firewall"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/pin:
    commands: ["make", "jobd/dol/pin"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/multicast:
    commands: ["make", "jobd/dol/multicast"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
  dol/pinl2mc:
    commands: ["make", "jobd/dol/pinl2mc"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
  dol/l4lb:
    commands: ["make", "jobd/dol/l4lb"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  #dol/dos:
    #commands: ["make", "jobd/dol/dos"]
    #owners: ["email:statikon@pensando.io"]
    #area:
    #sub-area:
    #feature:
  dol/recirc:
    commands: ["make", "jobd/dol/recirc"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/classic:
    commands: ["make", "jobd/dol/classic"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
  dol/classicl2mc:
    commands: ["make", "jobd/dol/classicl2mc"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
  dol/parser:
    commands: ["make", "jobd/dol/parser"]
    owners: ["email:pbhide@pensando.io"]
    area:
    sub-area:
    feature:
  dol/telemetry:
    commands: ["make", "jobd/dol/telemetry"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
  dol/p4pt:
    commands: ["make", "jobd/dol/p4pt"]
    owners: ["email:jainvipin@pensando.io"]
    area:
    sub-area:
    feature:
  dol/app_redir:
    commands: ["make", "jobd/dol/app_redir"]
    owners: ["email:tuyenq@pensando.io"]
    area:
    sub-area:
    feature:
  dol/basetopo:
    commands: ["make", "jobd/dol/basetopo"]
    owners: ["email:vikasd@pensando.io"]
    area:
    sub-area:
    feature:
  dol/swphv:
    commands: ["make", "jobd/dol/swphv"]
    owners: ["email:shaleman@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== GFT Tests ===========================
  dol/gft:
    commands: ["make", "PIPELINE=gft", "jobd/dol/gft"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  dol/gft/rdma:
    commands: ["make", "PIPELINE=gft", "jobd/dol/gft/rdma"]
    owners: ["email:ksmurty@pensando.io"]
    area:
    sub-area:
    feature:
  dol/gft/rdma_l2l:
    commands: ["make", "PIPELINE=gft", "jobd/dol/gft/rdma_l2l"]
    owners: ["email:ksmurty@pensando.io"]
    area:
    sub-area:
    feature:
  gft/gtest:
    commands: ["make", "PIPELINE=gft", "jobd/gft/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== MBT Tests ===========================
  mbt/base:
    commands: ["make", "jobd/mbt/base"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  mbt/networking:
    commands: ["make", "jobd/mbt/networking"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
  mbt/firewall:
    commands: ["make", "jobd/mbt/firewall"]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:
  mbt/alg:
    commands: ["make", "jobd/mbt/alg"]
    owners: ["email:pavramas@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== Make Infra Tests ===========================
  #make/sdk:
  # commands: ["make", "jobd/make/sdk"]
  # owners: ["email:statikon@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #make/nic:
  # commands: ["make", "jobd/make/nic"]
  # owners: ["email:vikasd@pensando.io"]
  # area:
  # sub-area:
  # feature:

  codesync:
    commands: ["make", "jobd/codesync" ]
    owners: ["email:statikon@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== Apollo2 Tests ===========================
  apollo/gtest:
    commands: ["make", "PIPELINE=apollo", "jobd/apollo/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== E2E DOL Tests ===========================
  #dol/e2e/tlsproxy:
  # commands: ["make", "jobd/dol/e2e/tlsproxy"]
  # owners: ["email:raghava@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #dol/e2e/tlsproxy/v6:
  # commands: ["make", "jobd/dol/e2e/v6tlsproxy"]
  # owners: ["email:raghava@pensando.io"]
  # area:
  # sub-area:
  # feature:
  dol/e2e/eplearn:
    commands: ["make", "jobd/dol/e2e/eplearn"]
    owners: ["email:sudhiaithal@pensando.io"]
    area:
    sub-area:
    feature:
  #dol/e2e/alg:
  # commands: ["make", "jobd/dol/e2e/alg"]
  # owners: ["email:pavramas@pensando.io"]
  # area:
  # sub-area:
  # feature:
  dol/e2e/l7:
    commands: ["make", "jobd/dol/e2e/l7"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== Agent Tests ===========================
  agent:
    commands: ["make", "jobd/agent"]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:
  e2e/naples-sim:
    commands: ["make", "jobd/e2e/naples-sim"]
    owners: ["email:sudhiaithal@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== IRIS-C Tests ===========================
  # iris-c gtests
  #filter/gtest:
  # commands: ["make", "jobd/filter/gtest"]
  # owners: ["email:saratk@pensando.io"]
  # area:
  # sub-area:
  # feature:

  # ====================== Upg Mgr Tests ===========================
  upgrade_manager/gtests:
    commands: ["make", "jobd/upgrade_manager/gtests"]
    owners: ["email:arathore@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== Nic Mgr Tests ===========================
  nicmgr/gtest:
   commands: ["make", "jobd/nicmgr/gtest"]
   owners: ["email:bharat@pensando.io"]
   area:
   sub-area:
   feature:
  nicmgr/gtest_classic:
   commands: ["make", "jobd/nicmgr/gtest_classic"]
   owners: ["email:bharat@pensando.io"]
   area:
   sub-area:
   feature:

  #coremgr:
  # commands: ["sh", "-c", "cd /sw && make pull-assets && cd nic && bazel build //nic/sysmgr/coremgr/... && cd /sw/nic/sysmgr/coremgr/test && ./test.sh; ret=$? ; exit $ret" ]
  # owners: ["email:dbarsky@pensando.io"]
  # area:
  # sub-area:
  # feature:

  delphi:
    commands: ["sh", "-c", "cd /sw/nic && make && cd ./delphi && make test" ]
    owners: ["email:shaleman@pensando.io"]
    area:
    sub-area:
    feature:
  #upgmgr:
  # commands: ["sh", "-c", "cd /sw/nic && bazel build //nic/upgrade_manager/... && bazel test //nic/upgrade_manager/... --jobs 1 --cache_test_results=no --test_output=all" ]
  # owners: ["email:arathore@pensando.io"]
  # area:
  # sub-area:
  # feature:
  sysmgr:
    commands: ["sh", "-c", "cd /sw/nic/sysmgr/test && ./test.sh" ]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
  penlog:
    commands: ["sh", "-c", "cd /sw/nic/utils/penlog/test && ./run_test.sh"]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
  venice:
    commands: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && make checks && LD_LIBRARY_PATH=$GOPATH/src/github.com/pensando/sw/nic/build/x86_64/iris/lib/ TRACKER_URL=\"tracker.test.pensando.io\" make unit-test-cover; ret=$? ; make sanity_logs ; exit $ret" ]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
  - /sw/iota/iota_sanity_logs.tar.gz

warmd:
  target:
    commands: ["make", "jobd/iota/base"]
    owners: ["email:sudhiaithal@pensando.io"]
  create:
    image: build-112
    count: 6
    resources:
      cpus  : 8
      memory: 20
      pvt-networks:
            - control
      data-networks:
            - data-1
            - data-2
  provision:
    username: vm
    password: vm
    # additional vars to pass to ansible.
    vars:
