---
targets:
  main: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make -j4 all && make run-gtests && make clean && make sanity_logs" ]
  halctl: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make -j4 all &&  cd $GOPATH/src/github.com/pensando/sw/nic/agent/cmd/halctl && go test" ]
  arm_build: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make ARCH=aarch64 nic && make ARCH=aarch64 sanity-tests && make ARCH=aarch64 gtests && make clean && make sanity_logs" ]
  arm_haps_build: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make clean && make PLATFORM=haps ARCH=aarch64 nic && make PLATFORM=haps ARCH=aarch64 sanity-tests && make PLATFORM=haps ARCH=aarch64 gtests && make clean && make sanity_logs" ]
  storage:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --storage && make sanity_logs" ]
  # config:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --configtest && make sanity_logs" ]
  rdma:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo rdma --feature rdma && make sanity_logs" ]
  rdma_ext:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo rdma --feature rdma_ext,rdma_perf && make sanity_logs" ]
  fte:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo fte --feature fte --lite && make sanity_logs" ]
  fte2:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo fte --feature fte2 --lite && make sanity_logs" ]
  ftevxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo fte --feature ftevxlan --lite && make sanity_logs" ]
  alg: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py --topo alg --feature alg && make sanity_logs" ]
  norm: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo norm --feature norm && make sanity_logs" ]
  eth:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo eth --feature eth && make sanity_logs" ]
  acl:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo acl --feature acl && make sanity_logs" ]
  proxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo proxy --feature proxy,proxy_fte && make sanity_logs" ]
  e2etlsproxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo proxy --feature proxy --config-only --e2e-tls-dol && make sanity_logs" ]
  v6e2etlsproxy:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo proxy --feature proxy --config-only --v6-e2e-tls-dol && make sanity_logs" ]
  e2enetworking:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo e2e --feature e2e --sub e2e --e2e-mode auto --cfgjson conf/dol.conf && make sanity_logs" ]
  e2ealg: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo alg --feature e2e --sub alg --e2e-mode auto --cfgjson conf/dol.conf && make sanity_logs" ]
  ipsec:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo proxy --feature ipsec --no_error_check && make sanity_logs" ]
  networking:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo up2up --feature networking && make sanity_logs" ]
  vxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo vxlan --feature vxlan && make sanity_logs" ]
  ipsg:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo eth --feature ipsg && make sanity_logs" ]
  firewall:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo firewall --feature firewall && make sanity_logs" ]
  # admin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo admin --feature admin && make sanity_logs" ]
  pin:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo fte --feature fte,hostpin --hostpin --lite && make sanity_logs" ]
  pin2:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo fte --feature fte2 --hostpin --lite && make sanity_logs" ]
  pinvxlan:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo fte --feature ftevxlan,hpvxlan --hostpin --lite && make sanity_logs" ]
  agent: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make pull-assets && make checks && cd nic && make nic && make sanity-tests && bash agent/netagent/scripts/sanity.sh && make sanity_logs" ]
  agent-single-threaded: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make pull-assets && make checks && cd nic && make nic && make sanity-tests && bash agent/netagent/scripts/sanity.sh single-threaded && make sanity_logs" ]
  multicast:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo multicast --feature multicast && make sanity_logs" ]
  pinl2mc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo multicast --feature pinl2mc --hostpin && make sanity_logs" ]
  l4lb:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo l4lb --feature l4lb && make sanity_logs" ]
  dos:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo dos --feature dos && make sanity_logs" ]
  recirc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo recirc --feature recirc && make sanity_logs" ]
  classic:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo classic --feature classic --classic && make sanity_logs" ]
  classicl2mc:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo classic --feature classicl2mc --classic && make sanity_logs" ]
  parser:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo parser --feature parser && make sanity_logs" ]
  telemetry:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo telemetry --feature telemetry && make sanity_logs" ]
  p4pt:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py --topo p4pt --feature p4pt && make sanity_logs" ]
  app_redir:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo app_redir --feature app_redir && make sanity_logs" ]
  e2el7:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo proxy --feature proxy --config-only --e2e-l7-dol && make sanity_logs" ]
  # configtoggle: ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo up2up --feature networking --configtoggle && make sanity_logs" ]
  gft/gtest:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make gft && ./run.py --gft_gtest && make run-gft-gtests && make sanity_logs" ]
  gft:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make gft && ./run.py  --topo gft --feature gft --gft && make sanity_logs" ]
  base:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo base --feature eth_base,nw_base,rdma_base,proxy_base --lite && make sanity_logs" ]
  gft_rdma:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make gft && ./run.py  --topo rdma_gft --feature rdma_perf --gft && make sanity_logs" ] 
  swphv:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make nic && make sanity-tests && ./run.py  --topo proxy --feature swphv" ]
  proto-sync: ["sh", "-c", "cd /sw && make pull-assets && cd $GOPATH/src/github.com/pensando/sw/nic/agent/netagent/datapath/halproto && make proto-sync" ]
  hal-rtl/parser:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && make hal-rtl && ./run.py  --topo parser --feature parser && make sanity_logs" ]
  agent-arm-xcompile: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw make checks && env CGO_LDFLAGS=-L/tool/toolchain/aarch64-1.1/aarch64-linux-gnu/usr/include CC=/tool/toolchain/aarch64-1.1/bin/aarch64-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -a -v github.com/pensando/sw/nic/agent/cmd/netagent" ]

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
  - /sw/dol/dol.log
  - /sw/nic/hal.log
  - /sw/nic/model.log
  - /sw/nic/build.log
  - /sw/nic/storage_dol.log
  - /sw/nic/tcp_client.log
  - /sw/nic/tcp_server.log
  - /sw/nic/tls_server.log
  - /sw/nic/hntap.log
  - /sw/nic/tcp_client-v6.log
  - /sw/nic/tcp_server-v6.log
  - /sw/nic/tls_server-v6.log
  - /sw/nic/hntap-v6.log
  - /sw/nic/core.hal
  - /sw/nic/core.cap_model
  - /sw/nic/http_client.log
  - /sw/nic/http_server.log
  - /sw/nic/gen/capri_loader.conf
  - /sw/nic/pse.log
