---
targets:
  platform/drivers      : ["make", "jobd/platform/drivers"]
  gtests                : ["make", "jobd/gtests"]
  halctl                : ["make", "jobd/halctl"]

  # ====================== ARM Tests ===========================
  arm/build             : ["make", "ARCH=aarch64"]
  arm/build/haps        : ["make", "ARCH=aarch64", "PLATFORM=haps", "package-haps-dbg"]

  # ====================== Storage Tests ===========================
  storage               : ["make", "jobd/storage"]
  storage/perf          : ["make", "jobd/storage/perf"]
  storage/nvme          : ["make", "jobd/storage/nvme"]
  #storage/nvme_perf    : ["make", "jobd/storage/nvme_perf"]
  #storage/nicmgr        : ["make", "jobd/storage/nicmgr"]
  #Test running into locking issues - disabling for now
  #storage/combined     : ["make", "jobd/storage/combined"]

  # ====================== Config Tests ===========================
  #configtest           : ["make", "jobd/configtest"]

  # ====================== DOL Tests ===========================
  dol/rdma              : ["make", "jobd/dol/rdma"]
  dol/rdma_ext          : ["make", "jobd/dol/rdma_ext"]
  dol/fte               : ["make", "jobd/dol/fte"]
  dol/fte2              : ["make", "jobd/dol/fte2"]
  dol/ftevxlan          : ["make", "jobd/dol/ftevxlan"]
  dol/alg               : ["make", "jobd/dol/alg"]
  dol/norm              : ["make", "jobd/dol/norm"]
  dol/eth               : ["make", "jobd/dol/eth"]
  dol/acl               : ["make", "jobd/dol/acl"]
  dol/proxy             : ["make", "jobd/dol/proxy"]
  dol/ipsec             : ["make", "jobd/dol/ipsec"]
  dol/networking        : ["make", "jobd/dol/networking"]
  dol/vxlan             : ["make", "jobd/dol/vxlan"]
  dol/ipsg              : ["make", "jobd/dol/ipsg"]
  dol/firewall          : ["make", "jobd/dol/firewall"]
  dol/pin               : ["make", "jobd/dol/pin"]
  dol/multicast         : ["make", "jobd/dol/multicast"]
  dol/pinl2mc           : ["make", "jobd/dol/pinl2mc"]
  dol/l4lb              : ["make", "jobd/dol/l4lb"]
  dol/dos               : ["make", "jobd/dol/dos"]
  dol/recirc            : ["make", "jobd/dol/recirc"]
  dol/classic           : ["make", "jobd/dol/classic"]
  dol/classicl2mc       : ["make", "jobd/dol/classicl2mc"]
  dol/parser            : ["make", "jobd/dol/parser"]
  dol/telemetry         : ["make", "jobd/dol/telemetry"]
  dol/p4pt              : ["make", "jobd/dol/p4pt"]
  dol/app_redir         : ["make", "jobd/dol/app_redir"]
  dol/basetopo          : ["make", "jobd/dol/basetopo"]
  dol/swphv             : ["make", "jobd/dol/swphv"]

  # ====================== GFT Tests ===========================
  dol/gft               : ["make", "PIPELINE=gft", "jobd/dol/gft"]
  dol/gft/rdma          : ["make", "PIPELINE=gft", "jobd/dol/gft/rdma"]
  dol/gft/rdma_l2l      : ["make", "PIPELINE=gft", "jobd/dol/gft/rdma_l2l"]
  gft/gtest             : ["make", "PIPELINE=gft", "jobd/gft/gtest"]

  # ====================== MBT Tests ===========================
  mbt/base              : ["make", "jobd/mbt/base"]
  mbt/networking        : ["make", "jobd/mbt/networking"]
  mbt/firewall          : ["make", "jobd/mbt/firewall"]
  mbt/alg               : ["make", "jobd/mbt/alg"]

  # ====================== Make Infra Tests ===========================
  #make/sdk              : ["make", "jobd/make/sdk"]
  #make/nic              : ["make", "jobd/make/nic"]

  codesync              : ["make", "jobd/codesync" ]

  # ====================== Apollo2 Tests ===========================
  apollo/gtest         : ["make", "PIPELINE=apollo", "jobd/apollo/gtest"]

  # ====================== E2E DOL Tests ===========================
  #dol/e2e/tlsproxy      : ["make", "jobd/dol/e2e/tlsproxy"]
  #dol/e2e/tlsproxy/v6   : ["make", "jobd/dol/e2e/v6tlsproxy"]
  dol/e2e/eplearn       : ["make", "jobd/dol/e2e/eplearn"]
  #dol/e2e/alg           : ["make", "jobd/dol/e2e/alg"]
  dol/e2e/l7            : ["make", "jobd/dol/e2e/l7"]

  # ====================== Agent Tests ===========================
  agent                 : ["make", "jobd/agent"]
  e2e/naples-sim        : ["make", "jobd/e2e/naples-sim"]

  # ====================== IRIS-C Tests ===========================
  # iris-c gtests
  #filter/gtest          : ["make", "jobd/filter/gtest"]

  # ====================== Upg Mgr Tests ===========================
  upgrade_manager/gtests   : ["make", "jobd/upgrade_manager/gtests"]

  # ====================== Nic Mgr Tests ===========================
  #nicmgr/gtest          : ["make", "jobd/nicmgr/gtest"]
  #nicmgr/gtest_classic  : ["make", "jobd/nicmgr/gtest_classic"]

  #coremgr:  ["sh", "-c", "cd /sw && make pull-assets && cd nic && bazel build //nic/sysmgr/coremgr/... && cd /sw/nic/sysmgr/coremgr/test && ./test.sh; ret=$? ; exit $ret" ]

  delphi:  ["sh", "-c", "cd /sw/nic && make && cd ./delphi && make test && cd $GOPATH/src/github.com/pensando/sw && LD_LIBRARY_PATH=$GOPATH/src/github.com/pensando/sw/nic/build/x86_64/iris/lib/ go test -v ./nic/delphi/..." ]
  # upgmgr:  ["sh", "-c", "cd /sw/nic && bazel build //nic/upgrade_manager/... && bazel test //nic/upgrade_manager/... --jobs 1 --cache_test_results=no --test_output=all" ]
  sysmgr:  ["sh", "-c", "cd /sw/nic/sysmgr/test && ./test.sh" ]
  venice: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && make checks && LD_LIBRARY_PATH=$GOPATH/src/github.com/pensando/sw/nic/build/x86_64/iris/lib/ TRACKER_URL=\"tracker.test.pensando.io\" make unit-test-cover; ret=$? ; make sanity_logs ; exit $ret" ]

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"
rebase: true
logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz

#warmd:
#  target: [ "make", "jobd/iota/base" ]
#  create:
#    image: build-100
#    count: 6
#    resources:
#      cpus  : 8
#      memory: 20
#      pvt-networks:
#            - control
#      data-networks:
#            - data-1
#            - data-2
#  provision:
#    username: vm
#    password: vm
#    # additional vars to pass to ansible.
#    vars:
