---
targets:
  main: [ "sh", "-c", "make -j$(grep -c processor /proc/cpuinfo) && make gtest && ./run.py" ]
  gcov: [ "sh", "-c", "make V=1 GCOV=--coverage -j8 all" ]
image:
  name: "pensando/nic"
  bind_dir: "/sw/nic"
  extra_binds:
    /dol: /sw/dol
rebase: true
