---
version: 2.0
targets:
  apulu/gtest_1:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/gtest_1"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/gtest_2:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/gtest_2"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/vxlan:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/vxlan"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/lpm:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/lpm"]
    owners: ["email:sai@pensando.io", "email:param@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/rfc:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/rfc"]
    owners: ["email:sai@pensando.io", "email:param@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/learn:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/learn"]
    owners: ["email:sunil@pensando.io", "email:kalyanbade@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/pds_scale_test_mock:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/pds_scale_test_mock"]
    owners: ["email:kalyanbade@pensando.io", "email:akoradha@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/valgrind:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/gtests-valgrind"]
    owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  metaswitch/hals_test:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/metaswitch_hals_test"]
    owners: ["email:vijasrin@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  metaswitch/store_test:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/metaswitch_store_test"]
    owners: ["email:vijasrin@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
