---
version: 2.0
targets:
 apollo/tools/athena/gtests:
  #commands: ["make", "PIPELINE=athena", "jobd/athena/gtests"]
  commands: ["sh", "-c", "cd /sw/nic && JOB_ID=1 make PIPELINE=athena jobd/athena/gtests"]
  owners: ["email:ksmurty@pensando.io"]
  area:
  sub-area:
  feature:
  build-dependencies:
    - build-custom-athena-image

 athena_app/make:
  commands: ["sh", "-c", "cd /sw/nic && JOB_ID=1 make PIPELINE=athena jobd/athena_app/make"]
  owners: ["email:skittur@pensando.io"]
  area:
  sub-area:
  feature:
  build-dependencies:
    - build-custom-athena-image

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/apollo/tools/dev-docker-sanity/nic_sanity_logs.tar.gz
