// Code generated by protoc-gen-grpc-pensando DO NOT EDIT.

package genfields

func init() {
	globalMetricsMap["dropstats"] = make(map[string][]string)

	kindToFieldNameMap["DropMetrics"] = []string{
		"DropParseLenError",
		"DropHardwareError",
		"DropInputMapping",
		"DropMultiDestNotPinnedUplink",
		"DropFlowHit",
		"DropFlowMiss",
		"DropNacl",
		"DropIpsg",
		"DropIpNormalization",
		"DropTcpNormalization",
		"DropTcpRstWithInvalidAckNum",
		"DropTcpNonSynFirstPkt",
		"DropIcmpNormalization",
		"DropInputPropertiesMiss",
		"DropTcpOutOfWindow",
		"DropTcpSplitHandshake",
		"DropTcpWinZeroDrop",
		"DropTcpDataAfterFin",
		"DropTcpNonRstPktAfterRst",
		"DropTcpInvalidResponderFirstPkt",
		"DropTcpUnexpectedPkt",
		"DropSrcLifMismatch",
		"DropIcmpFragPkt",
	}
	globalMetricsMap["dropstats"]["DropMetrics"] = kindToFieldNameMap["DropMetrics"]

	metricsFieldAggFuncMap["DropMetrics"] = map[string]string{
		"DropFlowHit":                     "last",
		"DropFlowMiss":                    "last",
		"DropHardwareError":               "last",
		"DropIcmpFragPkt":                 "last",
		"DropIcmpNormalization":           "last",
		"DropInputMapping":                "last",
		"DropInputPropertiesMiss":         "last",
		"DropIpNormalization":             "last",
		"DropIpsg":                        "last",
		"DropMultiDestNotPinnedUplink":    "last",
		"DropNacl":                        "last",
		"DropParseLenError":               "last",
		"DropSrcLifMismatch":              "last",
		"DropTcpDataAfterFin":             "last",
		"DropTcpInvalidResponderFirstPkt": "last",
		"DropTcpNonRstPktAfterRst":        "last",
		"DropTcpNonSynFirstPkt":           "last",
		"DropTcpNormalization":            "last",
		"DropTcpOutOfWindow":              "last",
		"DropTcpRstWithInvalidAckNum":     "last",
		"DropTcpSplitHandshake":           "last",
		"DropTcpUnexpectedPkt":            "last",
		"DropTcpWinZeroDrop":              "last",
	}

}
