// Code generated by protoc-gen-grpc-pensando DO NOT EDIT.

package genfields

func init() {
	globalMetricsMap["ftestats"] = make(map[string][]string)

	kindToFieldNameMap["FteCPSMetrics"] = []string{
		"ConnectionsPerSecond",
		"MaxConnectionsPerSecond",
		"PacketsPerSecond",
		"MaxPacketsPerSecond",
	}
	globalMetricsMap["ftestats"]["FteCPSMetrics"] = kindToFieldNameMap["FteCPSMetrics"]

	kindToFieldNameMap["FteLifQMetrics"] = []string{
		"FlowMissPackets",
		"FlowRetransmitPackets",
		"L4RedirectPackets",
		"AlgControlFlowPackets",
		"TcpClosePackets",
		"TlsProxyPackets",
		"FteSpanPackets",
		"SoftwareQueuePackets",
		"QueuedTxPackets",
		"FreedTxPackets",
		"MaxSessionThresholdDrops",
		"SessionCreatesIgnored",
	}
	globalMetricsMap["ftestats"]["FteLifQMetrics"] = kindToFieldNameMap["FteLifQMetrics"]

	kindToFieldNameMap["SessionSummaryMetrics"] = []string{
		"TotalActiveSessions",
		"NumL2Sessions",
		"NumTcpSessions",
		"NumUdpSessions",
		"NumIcmpSessions",
		"NumDropSessions",
		"NumAgedSessions",
		"NumTcpResets",
		"NumIcmpErrors",
		"NumTcpCxnsetupTimeouts",
		"NumSessionCreateErrors",
		"NumTcpHalfOpenSessions",
		"NumOtherActiveSessions",
		"NumTcpSessionLimitDrops",
		"NumUdpSessionLimitDrops",
		"NumIcmpSessionLimitDrops",
		"NumOtherSessionLimitDrops",
	}
	globalMetricsMap["ftestats"]["SessionSummaryMetrics"] = kindToFieldNameMap["SessionSummaryMetrics"]

	metricsFieldAggFuncMap["FteCPSMetrics"] = map[string]string{
		"ConnectionsPerSecond":    "last",
		"MaxConnectionsPerSecond": "last",
		"MaxPacketsPerSecond":     "last",
		"PacketsPerSecond":        "last",
	}

	metricsFieldAggFuncMap["FteLifQMetrics"] = map[string]string{
		"AlgControlFlowPackets":    "last",
		"FlowMissPackets":          "last",
		"FlowRetransmitPackets":    "last",
		"FreedTxPackets":           "last",
		"FteSpanPackets":           "last",
		"L4RedirectPackets":        "last",
		"MaxSessionThresholdDrops": "last",
		"QueuedTxPackets":          "last",
		"SessionCreatesIgnored":    "last",
		"SoftwareQueuePackets":     "last",
		"TcpClosePackets":          "last",
		"TlsProxyPackets":          "last",
	}

	metricsFieldAggFuncMap["SessionSummaryMetrics"] = map[string]string{
		"NumAgedSessions":           "max",
		"NumDropSessions":           "max",
		"NumIcmpErrors":             "max",
		"NumIcmpSessionLimitDrops":  "max",
		"NumIcmpSessions":           "max",
		"NumL2Sessions":             "max",
		"NumOtherActiveSessions":    "max",
		"NumOtherSessionLimitDrops": "max",
		"NumSessionCreateErrors":    "max",
		"NumTcpCxnsetupTimeouts":    "max",
		"NumTcpHalfOpenSessions":    "max",
		"NumTcpResets":              "max",
		"NumTcpSessionLimitDrops":   "max",
		"NumTcpSessions":            "max",
		"NumUdpSessionLimitDrops":   "max",
		"NumUdpSessions":            "max",
		"TotalActiveSessions":       "max",
	}

}
