---
version: 2.0
targets:
  artemis/aarch64_build:
    commands: ["make", "PIPELINE=artemis", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:srikanth@pensando.io"]
    area:
    sub-area:
    feature:

  artemis/gtest:
    commands: ["make", "PIPELINE=artemis", "jobd/artemis/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

  artemis/pds_scale_test_mock:
    commands: ["make", "PIPELINE=artemis", "jobd/artemis/pds_scale_test_mock"]
    owners: ["email:vijasrin@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

  artemis/scale_test_sim:
    commands: ["make", "PIPELINE=artemis", "jobd/artemis/scale_test_sim"]
    owners: ["email:vijasrin@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

  #artemis/valgrind:
    #commands: ["make", "PIPELINE=artemis", "jobd/artemis/gtests-valgrind"]
    #owners: ["email:kalyanbade@pensando.io", "email:hareesh@pensando.io"]
    #area:
    #sub-area:
    #feature:
    #build-dependencies:
    #- build-artemis-x86

  artemis/dol/vxlan:
    commands: ["make", "PIPELINE=artemis", "jobd/dol/artemis/vxlan"]
    owners: ["email:param@pensando.io", "email:sai@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
