---
targets:
  iota/infra    : ["echo", "IOTA Infra Sanity"]

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/iota"
rebase: true
logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz

#warmd:
#  target: [ "make", "jobd/iota/base" ]
#  create:
#    image: build-94
#    count: 6
#    resources:
#      cpus  : 8
#      memory: 20
#      pvt-networks:
#            - control
#      data-networks:
#            - data-1
#            - data-2
#  provision:
#    username: vm
#    password: vm
#    # additional vars to pass to ansible.
#    vars:
