---
version: 2.0
targets:
  iota/infra:
    commands: ["sh", "-c", "cd /sw/iota && ./sanity.sh "]
    owners: ["email:sudhiaithal@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
     - build-iota

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/iota"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz

#warmd:
#  target:
#    commands: ["make", "-C", "/sw/nic", "jobd/iota/base"]
#    owners: ["email:sudhiaithal@pensando.io"]
#  create:
#    image: build-112
#    count: 6
#    resources:
#      cpus  : 8
#      memory: 20
#      pvt-networks:
#            - control
#      data-networks:
#            - data-1
#            - data-2
#  provision:
#    username: vm
#    password: vm
#    # additional vars to pass to ansible.
#    vars:
