// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pdsa.proto

/*
	Package venice is a generated protocol buffer package.

	It is generated from these files:
		pdsa.proto

	It has these top-level messages:
		GlobalOpts
		PdsaFields
*/
package venice

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GlobalOpts struct {
	OidLen          string `protobuf:"bytes,1,opt,name=OidLen,proto3" json:"OidLen,omitempty"`
	Mib             string `protobuf:"bytes,2,opt,name=Mib,proto3" json:"Mib,omitempty"`
	FillFn          string `protobuf:"bytes,3,opt,name=FillFn,proto3" json:"FillFn,omitempty"`
	ActionFn        string `protobuf:"bytes,4,opt,name=ActionFn,proto3" json:"ActionFn,omitempty"`
	UpdateForDelete bool   `protobuf:"varint,5,opt,name=UpdateForDelete,proto3" json:"UpdateForDelete,omitempty"`
	SpecMsg         string `protobuf:"bytes,6,opt,name=SpecMsg,proto3" json:"SpecMsg,omitempty"`
	FilterMib       string `protobuf:"bytes,7,opt,name=FilterMib,proto3" json:"FilterMib,omitempty"`
	FilterTypeField string `protobuf:"bytes,8,opt,name=FilterTypeField,proto3" json:"FilterTypeField,omitempty"`
	SkipExtToInt    bool   `protobuf:"varint,9,opt,name=SkipExtToInt,proto3" json:"SkipExtToInt,omitempty"`
	SkipMSMgmtLock  bool   `protobuf:"varint,10,opt,name=SkipMSMgmtLock,proto3" json:"SkipMSMgmtLock,omitempty"`
}

func (m *GlobalOpts) Reset()                    { *m = GlobalOpts{} }
func (m *GlobalOpts) String() string            { return proto.CompactTextString(m) }
func (*GlobalOpts) ProtoMessage()               {}
func (*GlobalOpts) Descriptor() ([]byte, []int) { return fileDescriptorPdsa, []int{0} }

func (m *GlobalOpts) GetOidLen() string {
	if m != nil {
		return m.OidLen
	}
	return ""
}

func (m *GlobalOpts) GetMib() string {
	if m != nil {
		return m.Mib
	}
	return ""
}

func (m *GlobalOpts) GetFillFn() string {
	if m != nil {
		return m.FillFn
	}
	return ""
}

func (m *GlobalOpts) GetActionFn() string {
	if m != nil {
		return m.ActionFn
	}
	return ""
}

func (m *GlobalOpts) GetUpdateForDelete() bool {
	if m != nil {
		return m.UpdateForDelete
	}
	return false
}

func (m *GlobalOpts) GetSpecMsg() string {
	if m != nil {
		return m.SpecMsg
	}
	return ""
}

func (m *GlobalOpts) GetFilterMib() string {
	if m != nil {
		return m.FilterMib
	}
	return ""
}

func (m *GlobalOpts) GetFilterTypeField() string {
	if m != nil {
		return m.FilterTypeField
	}
	return ""
}

func (m *GlobalOpts) GetSkipExtToInt() bool {
	if m != nil {
		return m.SkipExtToInt
	}
	return false
}

func (m *GlobalOpts) GetSkipMSMgmtLock() bool {
	if m != nil {
		return m.SkipMSMgmtLock
	}
	return false
}

type PdsaFields struct {
	Field                  string `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	SetFieldFn             string `protobuf:"bytes,2,opt,name=SetFieldFn,proto3" json:"SetFieldFn,omitempty"`
	GetFieldFn             string `protobuf:"bytes,3,opt,name=GetFieldFn,proto3" json:"GetFieldFn,omitempty"`
	SetKeyOidIndex         string `protobuf:"bytes,4,opt,name=SetKeyOidIndex,proto3" json:"SetKeyOidIndex,omitempty"`
	GetKeyOidIndex         string `protobuf:"bytes,5,opt,name=GetKeyOidIndex,proto3" json:"GetKeyOidIndex,omitempty"`
	SetKeyOidFn            string `protobuf:"bytes,6,opt,name=SetKeyOidFn,proto3" json:"SetKeyOidFn,omitempty"`
	GetKeyOidFn            string `protobuf:"bytes,7,opt,name=GetKeyOidFn,proto3" json:"GetKeyOidFn,omitempty"`
	SetKeyOidLenIndex      string `protobuf:"bytes,8,opt,name=SetKeyOidLenIndex,proto3" json:"SetKeyOidLenIndex,omitempty"`
	GetKeyOidLenIndex      string `protobuf:"bytes,9,opt,name=GetKeyOidLenIndex,proto3" json:"GetKeyOidLenIndex,omitempty"`
	IgnoreIfEmpty          bool   `protobuf:"varint,10,opt,name=IgnoreIfEmpty,proto3" json:"IgnoreIfEmpty,omitempty"`
	IsZeroIPValid          bool   `protobuf:"varint,11,opt,name=IsZeroIPValid,proto3" json:"IsZeroIPValid,omitempty"`
	SetKeyOidAddrIndex     string `protobuf:"bytes,12,opt,name=SetKeyOidAddrIndex,proto3" json:"SetKeyOidAddrIndex,omitempty"`
	GetKeyOidAddrIndex     string `protobuf:"bytes,13,opt,name=GetKeyOidAddrIndex,proto3" json:"GetKeyOidAddrIndex,omitempty"`
	SetKeyOidAddrTypeIndex string `protobuf:"bytes,14,opt,name=SetKeyOidAddrTypeIndex,proto3" json:"SetKeyOidAddrTypeIndex,omitempty"`
	GetKeyOidAddrTypeIndex string `protobuf:"bytes,15,opt,name=GetKeyOidAddrTypeIndex,proto3" json:"GetKeyOidAddrTypeIndex,omitempty"`
	AddrTypeFieldName      string `protobuf:"bytes,16,opt,name=AddrTypeFieldName,proto3" json:"AddrTypeFieldName,omitempty"`
	AddrLenFieldName       string `protobuf:"bytes,17,opt,name=AddrLenFieldName,proto3" json:"AddrLenFieldName,omitempty"`
	KeysMsg                string `protobuf:"bytes,18,opt,name=KeysMsg,proto3" json:"KeysMsg,omitempty"`
	IsInternalField        bool   `protobuf:"varint,19,opt,name=IsInternalField,proto3" json:"IsInternalField,omitempty"`
	PackedElemSize         string `protobuf:"bytes,20,opt,name=PackedElemSize,proto3" json:"PackedElemSize,omitempty"`
	FilterType             string `protobuf:"bytes,21,opt,name=FilterType,proto3" json:"FilterType,omitempty"`
	FilterFieldLen         string `protobuf:"bytes,22,opt,name=FilterFieldLen,proto3" json:"FilterFieldLen,omitempty"`
}

func (m *PdsaFields) Reset()                    { *m = PdsaFields{} }
func (m *PdsaFields) String() string            { return proto.CompactTextString(m) }
func (*PdsaFields) ProtoMessage()               {}
func (*PdsaFields) Descriptor() ([]byte, []int) { return fileDescriptorPdsa, []int{1} }

func (m *PdsaFields) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *PdsaFields) GetSetFieldFn() string {
	if m != nil {
		return m.SetFieldFn
	}
	return ""
}

func (m *PdsaFields) GetGetFieldFn() string {
	if m != nil {
		return m.GetFieldFn
	}
	return ""
}

func (m *PdsaFields) GetSetKeyOidIndex() string {
	if m != nil {
		return m.SetKeyOidIndex
	}
	return ""
}

func (m *PdsaFields) GetGetKeyOidIndex() string {
	if m != nil {
		return m.GetKeyOidIndex
	}
	return ""
}

func (m *PdsaFields) GetSetKeyOidFn() string {
	if m != nil {
		return m.SetKeyOidFn
	}
	return ""
}

func (m *PdsaFields) GetGetKeyOidFn() string {
	if m != nil {
		return m.GetKeyOidFn
	}
	return ""
}

func (m *PdsaFields) GetSetKeyOidLenIndex() string {
	if m != nil {
		return m.SetKeyOidLenIndex
	}
	return ""
}

func (m *PdsaFields) GetGetKeyOidLenIndex() string {
	if m != nil {
		return m.GetKeyOidLenIndex
	}
	return ""
}

func (m *PdsaFields) GetIgnoreIfEmpty() bool {
	if m != nil {
		return m.IgnoreIfEmpty
	}
	return false
}

func (m *PdsaFields) GetIsZeroIPValid() bool {
	if m != nil {
		return m.IsZeroIPValid
	}
	return false
}

func (m *PdsaFields) GetSetKeyOidAddrIndex() string {
	if m != nil {
		return m.SetKeyOidAddrIndex
	}
	return ""
}

func (m *PdsaFields) GetGetKeyOidAddrIndex() string {
	if m != nil {
		return m.GetKeyOidAddrIndex
	}
	return ""
}

func (m *PdsaFields) GetSetKeyOidAddrTypeIndex() string {
	if m != nil {
		return m.SetKeyOidAddrTypeIndex
	}
	return ""
}

func (m *PdsaFields) GetGetKeyOidAddrTypeIndex() string {
	if m != nil {
		return m.GetKeyOidAddrTypeIndex
	}
	return ""
}

func (m *PdsaFields) GetAddrTypeFieldName() string {
	if m != nil {
		return m.AddrTypeFieldName
	}
	return ""
}

func (m *PdsaFields) GetAddrLenFieldName() string {
	if m != nil {
		return m.AddrLenFieldName
	}
	return ""
}

func (m *PdsaFields) GetKeysMsg() string {
	if m != nil {
		return m.KeysMsg
	}
	return ""
}

func (m *PdsaFields) GetIsInternalField() bool {
	if m != nil {
		return m.IsInternalField
	}
	return false
}

func (m *PdsaFields) GetPackedElemSize() string {
	if m != nil {
		return m.PackedElemSize
	}
	return ""
}

func (m *PdsaFields) GetFilterType() string {
	if m != nil {
		return m.FilterType
	}
	return ""
}

func (m *PdsaFields) GetFilterFieldLen() string {
	if m != nil {
		return m.FilterFieldLen
	}
	return ""
}

var E_PdsaSetGlobOpts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*GlobalOpts)(nil),
	Field:         82400,
	Name:          "venice.pdsaSetGlobOpts",
	Tag:           "bytes,82400,opt,name=pdsaSetGlobOpts",
	Filename:      "pdsa.proto",
}

var E_PdsaGetGlobOpts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*GlobalOpts)(nil),
	Field:         82401,
	Name:          "venice.pdsaGetGlobOpts",
	Tag:           "bytes,82401,opt,name=pdsaGetGlobOpts",
	Filename:      "pdsa.proto",
}

var E_PdsaFields = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*PdsaFields)(nil),
	Field:         83400,
	Name:          "venice.pdsaFields",
	Tag:           "bytes,83400,opt,name=pdsaFields",
	Filename:      "pdsa.proto",
}

func init() {
	proto.RegisterType((*GlobalOpts)(nil), "venice.GlobalOpts")
	proto.RegisterType((*PdsaFields)(nil), "venice.PdsaFields")
	proto.RegisterExtension(E_PdsaSetGlobOpts)
	proto.RegisterExtension(E_PdsaGetGlobOpts)
	proto.RegisterExtension(E_PdsaFields)
}
func (m *GlobalOpts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GlobalOpts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.OidLen) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.OidLen)))
		i += copy(dAtA[i:], m.OidLen)
	}
	if len(m.Mib) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.Mib)))
		i += copy(dAtA[i:], m.Mib)
	}
	if len(m.FillFn) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.FillFn)))
		i += copy(dAtA[i:], m.FillFn)
	}
	if len(m.ActionFn) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.ActionFn)))
		i += copy(dAtA[i:], m.ActionFn)
	}
	if m.UpdateForDelete {
		dAtA[i] = 0x28
		i++
		if m.UpdateForDelete {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.SpecMsg) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SpecMsg)))
		i += copy(dAtA[i:], m.SpecMsg)
	}
	if len(m.FilterMib) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.FilterMib)))
		i += copy(dAtA[i:], m.FilterMib)
	}
	if len(m.FilterTypeField) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.FilterTypeField)))
		i += copy(dAtA[i:], m.FilterTypeField)
	}
	if m.SkipExtToInt {
		dAtA[i] = 0x48
		i++
		if m.SkipExtToInt {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.SkipMSMgmtLock {
		dAtA[i] = 0x50
		i++
		if m.SkipMSMgmtLock {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *PdsaFields) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PdsaFields) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Field) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.Field)))
		i += copy(dAtA[i:], m.Field)
	}
	if len(m.SetFieldFn) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SetFieldFn)))
		i += copy(dAtA[i:], m.SetFieldFn)
	}
	if len(m.GetFieldFn) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.GetFieldFn)))
		i += copy(dAtA[i:], m.GetFieldFn)
	}
	if len(m.SetKeyOidIndex) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SetKeyOidIndex)))
		i += copy(dAtA[i:], m.SetKeyOidIndex)
	}
	if len(m.GetKeyOidIndex) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.GetKeyOidIndex)))
		i += copy(dAtA[i:], m.GetKeyOidIndex)
	}
	if len(m.SetKeyOidFn) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SetKeyOidFn)))
		i += copy(dAtA[i:], m.SetKeyOidFn)
	}
	if len(m.GetKeyOidFn) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.GetKeyOidFn)))
		i += copy(dAtA[i:], m.GetKeyOidFn)
	}
	if len(m.SetKeyOidLenIndex) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SetKeyOidLenIndex)))
		i += copy(dAtA[i:], m.SetKeyOidLenIndex)
	}
	if len(m.GetKeyOidLenIndex) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.GetKeyOidLenIndex)))
		i += copy(dAtA[i:], m.GetKeyOidLenIndex)
	}
	if m.IgnoreIfEmpty {
		dAtA[i] = 0x50
		i++
		if m.IgnoreIfEmpty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.IsZeroIPValid {
		dAtA[i] = 0x58
		i++
		if m.IsZeroIPValid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.SetKeyOidAddrIndex) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SetKeyOidAddrIndex)))
		i += copy(dAtA[i:], m.SetKeyOidAddrIndex)
	}
	if len(m.GetKeyOidAddrIndex) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.GetKeyOidAddrIndex)))
		i += copy(dAtA[i:], m.GetKeyOidAddrIndex)
	}
	if len(m.SetKeyOidAddrTypeIndex) > 0 {
		dAtA[i] = 0x72
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.SetKeyOidAddrTypeIndex)))
		i += copy(dAtA[i:], m.SetKeyOidAddrTypeIndex)
	}
	if len(m.GetKeyOidAddrTypeIndex) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.GetKeyOidAddrTypeIndex)))
		i += copy(dAtA[i:], m.GetKeyOidAddrTypeIndex)
	}
	if len(m.AddrTypeFieldName) > 0 {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.AddrTypeFieldName)))
		i += copy(dAtA[i:], m.AddrTypeFieldName)
	}
	if len(m.AddrLenFieldName) > 0 {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.AddrLenFieldName)))
		i += copy(dAtA[i:], m.AddrLenFieldName)
	}
	if len(m.KeysMsg) > 0 {
		dAtA[i] = 0x92
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.KeysMsg)))
		i += copy(dAtA[i:], m.KeysMsg)
	}
	if m.IsInternalField {
		dAtA[i] = 0x98
		i++
		dAtA[i] = 0x1
		i++
		if m.IsInternalField {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.PackedElemSize) > 0 {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.PackedElemSize)))
		i += copy(dAtA[i:], m.PackedElemSize)
	}
	if len(m.FilterType) > 0 {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.FilterType)))
		i += copy(dAtA[i:], m.FilterType)
	}
	if len(m.FilterFieldLen) > 0 {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintPdsa(dAtA, i, uint64(len(m.FilterFieldLen)))
		i += copy(dAtA[i:], m.FilterFieldLen)
	}
	return i, nil
}

func encodeVarintPdsa(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *GlobalOpts) Size() (n int) {
	var l int
	_ = l
	l = len(m.OidLen)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.Mib)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.FillFn)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.ActionFn)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	if m.UpdateForDelete {
		n += 2
	}
	l = len(m.SpecMsg)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.FilterMib)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.FilterTypeField)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	if m.SkipExtToInt {
		n += 2
	}
	if m.SkipMSMgmtLock {
		n += 2
	}
	return n
}

func (m *PdsaFields) Size() (n int) {
	var l int
	_ = l
	l = len(m.Field)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.SetFieldFn)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.GetFieldFn)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.SetKeyOidIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.GetKeyOidIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.SetKeyOidFn)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.GetKeyOidFn)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.SetKeyOidLenIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.GetKeyOidLenIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	if m.IgnoreIfEmpty {
		n += 2
	}
	if m.IsZeroIPValid {
		n += 2
	}
	l = len(m.SetKeyOidAddrIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.GetKeyOidAddrIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.SetKeyOidAddrTypeIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.GetKeyOidAddrTypeIndex)
	if l > 0 {
		n += 1 + l + sovPdsa(uint64(l))
	}
	l = len(m.AddrTypeFieldName)
	if l > 0 {
		n += 2 + l + sovPdsa(uint64(l))
	}
	l = len(m.AddrLenFieldName)
	if l > 0 {
		n += 2 + l + sovPdsa(uint64(l))
	}
	l = len(m.KeysMsg)
	if l > 0 {
		n += 2 + l + sovPdsa(uint64(l))
	}
	if m.IsInternalField {
		n += 3
	}
	l = len(m.PackedElemSize)
	if l > 0 {
		n += 2 + l + sovPdsa(uint64(l))
	}
	l = len(m.FilterType)
	if l > 0 {
		n += 2 + l + sovPdsa(uint64(l))
	}
	l = len(m.FilterFieldLen)
	if l > 0 {
		n += 2 + l + sovPdsa(uint64(l))
	}
	return n
}

func sovPdsa(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPdsa(x uint64) (n int) {
	return sovPdsa(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GlobalOpts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPdsa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GlobalOpts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GlobalOpts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OidLen", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OidLen = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mib", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mib = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillFn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FillFn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionFn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionFn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateForDelete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UpdateForDelete = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpecMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterMib", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilterMib = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterTypeField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilterTypeField = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipExtToInt", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SkipExtToInt = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipMSMgmtLock", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SkipMSMgmtLock = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPdsa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPdsa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PdsaFields) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPdsa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PdsaFields: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PdsaFields: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetFieldFn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetFieldFn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetFieldFn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GetFieldFn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetKeyOidIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetKeyOidIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetKeyOidIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GetKeyOidIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetKeyOidFn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetKeyOidFn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetKeyOidFn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GetKeyOidFn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetKeyOidLenIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetKeyOidLenIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetKeyOidLenIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GetKeyOidLenIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreIfEmpty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IgnoreIfEmpty = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsZeroIPValid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsZeroIPValid = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetKeyOidAddrIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetKeyOidAddrIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetKeyOidAddrIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GetKeyOidAddrIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetKeyOidAddrTypeIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetKeyOidAddrTypeIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetKeyOidAddrTypeIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GetKeyOidAddrTypeIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddrTypeFieldName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddrTypeFieldName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddrLenFieldName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddrLenFieldName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeysMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeysMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsInternalField", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsInternalField = bool(v != 0)
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackedElemSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PackedElemSize = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilterType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterFieldLen", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPdsa
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilterFieldLen = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPdsa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPdsa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPdsa(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPdsa
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPdsa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPdsa
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPdsa
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPdsa(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPdsa = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPdsa   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pdsa.proto", fileDescriptorPdsa) }

var fileDescriptorPdsa = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x55, 0xda, 0x5f, 0xd3, 0x66, 0xfb, 0x7f, 0x7f, 0xa5, 0x5a, 0x55, 0x10, 0xa2, 0x0a, 0xa1,
	0x0a, 0x21, 0x57, 0x02, 0x89, 0x43, 0x6f, 0x45, 0xd4, 0x96, 0xd5, 0x84, 0x54, 0x71, 0xe1, 0xc0,
	0x05, 0x39, 0xf1, 0x34, 0xb2, 0xea, 0xac, 0x2d, 0xef, 0x82, 0x1a, 0xae, 0x1c, 0xf9, 0x56, 0x9c,
	0x7a, 0xe4, 0x23, 0x94, 0x7e, 0x0e, 0x0e, 0x68, 0x76, 0x9c, 0xf8, 0x5f, 0x10, 0xe2, 0xb6, 0xf3,
	0xe6, 0xcd, 0x9b, 0xd5, 0x68, 0xe6, 0x31, 0x96, 0x04, 0xca, 0xb7, 0x92, 0x34, 0xd6, 0x31, 0x6f,
	0x7e, 0x06, 0x19, 0x8e, 0xe0, 0xa0, 0x33, 0x8e, 0xe3, 0x71, 0x04, 0xc7, 0x06, 0x1d, 0x7e, 0xba,
	0x3a, 0x0e, 0x40, 0x8d, 0xd2, 0x30, 0xd1, 0x71, 0x4a, 0xcc, 0xc3, 0xef, 0x4b, 0x8c, 0x39, 0x51,
	0x3c, 0xf4, 0xa3, 0x7e, 0xa2, 0x15, 0xdf, 0x67, 0xcd, 0x7e, 0x18, 0x74, 0x41, 0x8a, 0x46, 0xa7,
	0x71, 0xd4, 0x1a, 0x64, 0x11, 0xdf, 0x61, 0xcb, 0xbd, 0x70, 0x28, 0x96, 0x0c, 0x88, 0x4f, 0x64,
	0xda, 0x61, 0x14, 0xd9, 0x52, 0x2c, 0x13, 0x93, 0x22, 0x7e, 0xc0, 0xd6, 0x4e, 0x47, 0x3a, 0x8c,
	0xa5, 0x2d, 0xc5, 0x7f, 0x26, 0x33, 0x8f, 0xf9, 0x11, 0xdb, 0x7e, 0x97, 0x04, 0xbe, 0x06, 0x3b,
	0x4e, 0xdf, 0x40, 0x04, 0x1a, 0xc4, 0x4a, 0xa7, 0x71, 0xb4, 0x36, 0xa8, 0xc2, 0x5c, 0xb0, 0x55,
	0x2f, 0x81, 0x51, 0x4f, 0x8d, 0x45, 0xd3, 0x88, 0xcc, 0x42, 0xfe, 0x90, 0xb5, 0xec, 0x30, 0xd2,
	0x90, 0xe2, 0x7f, 0x56, 0x4d, 0x2e, 0x07, 0xb0, 0x03, 0x05, 0x97, 0xd3, 0x04, 0xec, 0x10, 0xa2,
	0x40, 0xac, 0x19, 0x4e, 0x15, 0xe6, 0x87, 0x6c, 0xc3, 0xbb, 0x0e, 0x93, 0xb3, 0x1b, 0x7d, 0x19,
	0xbb, 0x52, 0x8b, 0x96, 0xf9, 0x48, 0x09, 0xe3, 0x4f, 0xd9, 0x16, 0xc6, 0x3d, 0xaf, 0x37, 0x9e,
	0xe8, 0x6e, 0x3c, 0xba, 0x16, 0xcc, 0xb0, 0x2a, 0xe8, 0xe1, 0xaf, 0x26, 0x63, 0x17, 0x81, 0xf2,
	0x8d, 0xb2, 0xe2, 0x7b, 0x6c, 0x85, 0x5a, 0xd3, 0x0c, 0x29, 0xe0, 0x6d, 0xc6, 0x3c, 0xd0, 0xe6,
	0x6d, 0xcb, 0x6c, 0x92, 0x05, 0x04, 0xf3, 0x4e, 0x9e, 0xa7, 0xa1, 0x16, 0x10, 0xf3, 0x19, 0xd0,
	0xe7, 0x30, 0xed, 0x87, 0x81, 0x2b, 0x03, 0xb8, 0xc9, 0xc6, 0x5b, 0x41, 0x91, 0xe7, 0x94, 0x79,
	0x2b, 0xc4, 0x2b, 0xa3, 0xbc, 0xc3, 0xd6, 0xe7, 0x95, 0xb6, 0xcc, 0xc6, 0x5c, 0x84, 0x90, 0xe1,
	0x14, 0x18, 0x34, 0xec, 0x22, 0xc4, 0x9f, 0xb3, 0xdd, 0x79, 0x41, 0x17, 0x24, 0xb5, 0xa3, 0x81,
	0xd7, 0x13, 0xc8, 0x76, 0x6a, 0xec, 0x16, 0xb1, 0x6b, 0x09, 0xfe, 0x84, 0x6d, 0xba, 0x63, 0x19,
	0xa7, 0xe0, 0x5e, 0x9d, 0x4d, 0x12, 0x3d, 0xcd, 0x66, 0x5f, 0x06, 0x0d, 0x4b, 0x7d, 0x80, 0x34,
	0x76, 0x2f, 0xde, 0xfb, 0x51, 0x18, 0x88, 0xf5, 0x8c, 0x55, 0x04, 0xb9, 0xc5, 0xf8, 0xfc, 0x3b,
	0xa7, 0x41, 0x90, 0x52, 0xeb, 0x0d, 0xd3, 0x7a, 0x41, 0x06, 0xf9, 0x4e, 0x9d, 0xbf, 0x49, 0xfc,
	0x7a, 0x86, 0xbf, 0x62, 0xfb, 0x25, 0x15, 0x5c, 0x33, 0xaa, 0xd9, 0x32, 0x35, 0x7f, 0xc8, 0x62,
	0x9d, 0xb3, 0xb8, 0x6e, 0x9b, 0xea, 0x16, 0x67, 0x71, 0x92, 0x33, 0xc0, 0xac, 0xc7, 0x5b, 0x7f,
	0x02, 0x62, 0x87, 0x26, 0x59, 0x4b, 0xf0, 0x67, 0x6c, 0x07, 0xc1, 0x2e, 0xc8, 0x9c, 0xbc, 0x6b,
	0xc8, 0x35, 0x1c, 0x0f, 0xef, 0x1c, 0xa6, 0x0a, 0x0f, 0x8f, 0xd3, 0xe1, 0x65, 0x21, 0x9e, 0x96,
	0xab, 0x5c, 0xa9, 0x21, 0x95, 0x7e, 0x44, 0xfb, 0xfd, 0x3f, 0x1d, 0x6f, 0x05, 0xc6, 0x0d, 0xbc,
	0xf0, 0x47, 0xd7, 0x10, 0x9c, 0x45, 0x30, 0xf1, 0xc2, 0x2f, 0x20, 0xf6, 0x68, 0x03, 0xcb, 0x28,
	0x6e, 0x7c, 0x7e, 0x95, 0xe2, 0x01, 0x6d, 0x7c, 0x8e, 0xa0, 0x0e, 0x45, 0x46, 0x16, 0x4d, 0x69,
	0x9f, 0x74, 0xca, 0xe8, 0xc9, 0x47, 0xb6, 0x8d, 0xde, 0xe7, 0x81, 0x46, 0x27, 0x33, 0x3e, 0xf6,
	0xd8, 0x22, 0xe7, 0xb3, 0x66, 0xce, 0x67, 0xf5, 0x40, 0x29, 0x7f, 0x0c, 0xfd, 0x04, 0xbd, 0x48,
	0x89, 0xbb, 0xaf, 0x78, 0x15, 0xeb, 0x2f, 0xb8, 0x45, 0x56, 0x69, 0xe5, 0x26, 0x38, 0xa8, 0xaa,
	0xcd, 0x1a, 0x38, 0xff, 0xd2, 0xe0, 0xe7, 0xdf, 0x1a, 0x14, 0xd4, 0x4e, 0x3c, 0x72, 0xef, 0xcc,
	0x3f, 0x1e, 0xd5, 0xb4, 0x4d, 0x62, 0xa6, 0x7c, 0xfb, 0xad, 0xa2, 0x9c, 0x5b, 0xcf, 0xa0, 0x20,
	0xf3, 0x7a, 0xe3, 0xf6, 0xbe, 0xdd, 0xf8, 0x71, 0xdf, 0x6e, 0xdc, 0xdd, 0xb7, 0x1b, 0xc3, 0xa6,
	0x11, 0x7b, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x94, 0xc2, 0x62, 0xd1, 0x27, 0x06, 0x00, 0x00,
}
