---
targets:
#  venice-ui: [ "sh", "-c", "cd venice/ui/web-app-framework && npm install && npm rebuild node-sass --force && ng test --env=prod --watch false --browser ChromeHeadlessCI && npm run pack && cd ../venice-sdk && npm install && cd ../webapp &&  npm rebuild node-sass --force && npm install  ../web-app-framework/dist/web-app-framework-0.0.0.tgz && npm install && ng -v && ng test --env=prod --watch false  -sm=false --browser ChromeHeadlessCI" ]
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
