---
version: 2.0
targets:
  venice-ui:
    commands: [ "bash", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && mkdir bin && make ui-unit-test-cover && make ui-checks && ./tools/scripts/check-local-files.sh" ]
    owners: ["email:jeffhu@pensando.io"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
