# Scale config file representative of Goldman per NAPLES node scale configs
# The ordering here will be the order of objects created via Agent REST
---
objects:
- kind: Namespace
  name: scale-vrf
  count: 4
  rest-endpoint: "/api/namespaces/"
  spec-file: "generated/namespaces.json"
- kind: Network
  name: scale-nw
  count: 8
  rest-endpoint: "/api/networks/"
  spec-file: "generated/networks.json"
- kind: Endpoint
  name: scale-ep
  count: 32
  rest-endpoint: "/api/endpoints/"
  spec-file: "generated/endpoints.json"
- kind: MirrorSession
  name: scale-mirror
  rest-endpoint: "/api/mirror/sessions/"
  count: 8
  spec-file: "generated/mirrors.json"
- kind: SGPolicy
  name: scale-sg-policy
  count: 1
  rest-endpoint: "/api/security/policies/"
  spec-file: "generated/16_rules.json"
- kind: IPSecSAEncrypt
  name: scale-ipsec-encrypt-sa 
  count: 1
  rest-endpoint: "/api/ipsec/encryption/"
  spec-file: "generated/ipsec_encryption.json"
- kind: IPSecSADecrypt
  name: scale-ipsec-decrypt-sa
  count: 1
  rest-endpoint: "/api/ipsec/decryption/"
  spec-file: "generated/ipsec_decryption.json"
- kind: IPSecPolicy
  name: scale-ipsec-policies
  count: 2
  rest-endpoint: "/api/ipsec/policies/"
  spec-file: "generated/ipsec_policies.json"
