---
version: 2.0
targets:

  gtests:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw/nic && make ARCH=x86_64 && make jobd/gtests/platform/penutil"]
    owners: ["email:platform-team@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/sw"
  work_dir: "/sw/platform"
