---
targets:
  build_x86-64: [ "sh", "-c", "cd /sw/nic && make ARCH=x86_64" ]
  build_aarch64: [ "sh", "-c", "cd /sw/nic && make ARCH=aarch64" ]
  ##nicmgr_gtest: [ "sh", "-c", "make && cd /sw/nic && ./run.py --nicmgr_gtest" ]
  ##nicmgr_classic_gtest: [ "sh", "-c", "make && cd /sw/nic && ./run.py --nicmgr_gtest --classic" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/platform"
rebase: true
#warmd:
#  target: [ "sh", "-c", "cd /sw && make e2e-turin && test/bin/e2e-turin  test --topo-file 2_naples_qemu_node.yaml" ]
#  create:
#    image: build-38
#    count: 2
#    resources:
#      cpus: 8
#      memory: 16
#      pvt-networks:
#            - data
#            - control
#
#  provision:
#    username: vm
#    password: vm
