---
targets:
  build_x86-64: [ "make", "all", "test" ]
  build_aarch64: [ "make", "BUILD_ARCHES=aarch64", "all", "test" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/platform"
rebase: true
