---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/local/bin/python"
  tasks:
  - name: spit out vm ip
    debug:
      msg: "VM ip {{ ansible_default_ipv4.address }} "
  - name: enable passwordless sudo
    lineinfile:
      path: /usr/local/etc/sudoers
      state: present
      regexp: '^%sudo\s'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'      
  - name: enable password auth
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PasswordAuthentication\s'
      line: 'PasswordAuthentication yes'
  - name: Restart service sshd
    service:
      name: sshd
      state: restarted
