---
targets:
  - [ "bash", "-c", "./ut_run.sh; err=$?; cat ut_run.log; exit $err" ]
  - [ "bash", "-c", "cd /sw/nic && make -j8 && ./run.py" ]
image:
  name: "pensando/dol"
  bind_dir: "/sw/dol"
  extra_binds:
    /nic: /sw/nic
rebase: true
references:
  - nic
