---
targets:
  infra: [ "bash", "-c", "./sanity.sh" ]
  regr: [ "bash", "-c", "./regression.sh" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/dol"
rebase: true
