---
version: 2.0
targets:
  infra:
    commands: [ "bash", "-c", "cd /sw/dol && ./sanity.sh" ]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:
  regr:
    commands: [ "bash", "-c", "cd /sw/dol && ./regression.sh" ]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:
  apollo/dol:
    commands: [ "bash", "-c", "cd /sw/dol && ./sanity_apollo.sh" ]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:
  artemis/dol:
    commands: [ "bash", "-c", "cd /sw/dol && ./sanity_artemis.sh" ]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:
  apulu/dol:
    commands: [ "bash", "-c", "cd /sw/dol && ./sanity_apulu.sh" ]
    owners: ["email:param@pensando.io"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/sw"
  work_dir: "/sw/dol"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
