---
version: 2.0
targets:
  dummy:
    commands: [ "bash", "-c", "cd /sw/dol/apollo" ]
    owners: ["email:kalyanbade@pensando.io"]
    area:
    sub-area:
    feature:
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/dol/apollo"
rebase: true
