---
version: 2.0
targets:
  metaswitch/build:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/gtest_1"]
    owners: ["email:vijasrin@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /usr/src/github.com/pensando/sw/nic/nic_sanity_logs.tar.gz
