---
version: 2.0
targets:
  pciemgrd-capri:
    commands: ["sh", "-c", "make -C /sw/nic ASIC=capri jobd/platform/pciemgrd"]
    owners: ["email:brads@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  pciemgrd-elba:
    commands: ["sh", "-c", "make -C /sw/nic ASIC=elba jobd/platform/pciemgrd"]
    owners: ["email:brads@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86-elba
image:
  bind_dir: "/sw"
  work_dir: "/sw"
