---
version: 2.0
targets:
  pciemgrd-capri:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw/nic && make ASIC=capri PIPELINE=iris && make ASIC=capri -C ../platform/src/third-party/app/pciutils && make ASIC=capri BUILD_ARCH=x86_64 -C ../platform/src/app/pciemgrd/tests test"]
    owners: ["email:brads@pensando.io"]
    area:
    sub-area:
    feature:
  pciemgrd-elba:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw/nic && make ASIC=elba PIPELINE=iris && make ASIC=elba -C ../platform/src/third-party/app/pciutils && make ASIC=elba BUILD_ARCH=x86_64 -C ../platform/src/app/pciemgrd/tests test"]
    owners: ["email:brads@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/sw"
  work_dir: "/sw"
