---
targets:
  venice: [ "bash", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make && ./tools/scripts/check-local-files.sh" ]
  dep-checks: ["bash", "-c", "cd /go/src/github.com/pensando/sw && make ws-tools && dep check" ]
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
