---
version: 2.0
targets:
  venice:
    commands: [ "bash", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make && ./tools/scripts/check-local-files.sh" ]
    owners: ["email:ravi@pensando.io"]
    area:
    sub-area:
    feature:
  dep-checks:
    commands: ["bash", "-c", "cd /go/src/github.com/pensando/sw && make ws-tools && dep check" ]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
