---
version: 2.0
targets:
  dep-checks:
    commands: ["bash", "-c", "cd /go/src/github.com/pensando/sw && make ws-tools && dep check" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"

