version: 2.0
targets:
  venice:
    commands: [ "sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && make -C nic/agent/dscagent/types/apuluproto && make -C nic/apollo/agent/protos && make gen && VENICE_DEV=1 go test -timeout 30m -p 1 ./venice/... && VENICE_DEV=1 go test -timeout 1h -p 1 ./test/..." ]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:
  agent-iris:
    commands: [ "sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && make -C nic/sysmgr/proto && make -C nic/agent/dscagent && go test -v -tags iris -timeout 10m -p 1 ./nic/agent/dscagent/pipeline/iris/..." ]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:
  agent-apulu:
    commands: [ "sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && make -C nic/agent/dscagent/types/apuluproto && make -C nic/apollo/agent/protos && go build -o /tmp/netagent -tags apulu github.com/pensando/sw/nic/agent/cmd/netagent && rm -f /tmp/netagent && go test -v -tags apulu -timeout 10m -p 1 ./nic/agent/dscagent/pipeline/apulu/..." ]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"

