version: 2.0
targets:
  venice:
    commands: [ "sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && go test -p 1 ./venice/... && go test -p 1 ./test/..." ]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
