---
version: 2.0
targets:
  athena/gtests:
    commands: ["make", "PIPELINE=athena", "jobd/athena/gtests"]
    owners: ["email:skittur@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena-x86
    - build-athena-arm
    - build-custom-athena-image
    - build-athena-customer-arm

  athena/athena16_compile:
    commands: ["/bin/true"]
    owners: ["email:skittur@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena16-x86

  athena/gtests_sim:
    commands: ["make", "PIPELINE=athena", "jobd/athena/gtests_sim"]
    owners: ["email:skittur@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena-x86
    - build-athena-arm

  athena_app/session_aging_sim_simple:
    commands: ["make", "PIPELINE=athena", "jobd/athena_app/session_aging_sim_simple"]
    owners: ["email:tuyenq@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena-x86
    - build-athena-arm

  athena_app/session_aging_sim_medium:
    commands: ["make", "PIPELINE=athena", "jobd/athena_app/session_aging_sim_medium"]
    owners: ["email:tuyenq@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena-x86
    - build-athena-arm

  #athena_app/conntrack_aging_sim_simple:
  #  commands: ["make", "PIPELINE=athena", "jobd/athena_app/conntrack_aging_sim_simple"]
  #  owners: ["email:tuyenq@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-athena-x86
  #  - build-athena-arm

  #athena_app/conntrack_aging_sim_medium:
  #  commands: ["make", "PIPELINE=athena", "jobd/athena_app/conntrack_aging_sim_medium"]
  #  owners: ["email:tuyenq@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-athena-x86
  #  - build-athena-arm

  athena_app/standalone_arm_compile:
    commands: ["sh", "-c", "cd /sw/ && tar -zxvf athena-arm.tar.gz  && cd pensando_v1.0/athena_app && make ARCH=aarch64"]
    owners: ["email:murali@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena-customer-arm

  athena_app/standalone_x86_compile:
    commands: ["sh", "-c", "cd /sw/ && tar -zxvf athena-x86.tar.gz  && cd pensando_v1.0/athena_app && make"]
    owners: ["email:murali@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-athena-customer-x86

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
