basepath: "github.com/pensando/sw/utils/apigen/templates"
templates:
  - template: "doc.tmpl"
    outputpath: "doc.go"
  - template: "endpoints.tmpl"
    outputpath: "endpoints.go"
  - template: "services.tmpl"
    outputpath: "services.go"
  - template: "transport.tmpl"
    outputpath: "transport.go"
  - template: "grpcserver.tmpl"
    outputpath: "grpc/server/server.go"
  - template: "gateway.tmpl"
    outputpath: "gateway/gateway.go"
  - template: "grpcclient.tmpl"
    outputpath: "grpc/client/client.go"
  - template: "extpb.tmpl"
    outputpath: "service.pb.ext.go"

