basepath: "github.com/pensando/sw/utils/apigen/templates"
templates:
  - template: "doc.tmpl"
    outputpath: "{FILE}_doc.go"
  - template: "endpoints.tmpl"
    outputpath: "{FILE}_endpoints.go"
  - template: "services.tmpl"
    outputpath: "{FILE}_services.go"
  - template: "transport.tmpl"
    outputpath: "{FILE}_transport.go"
  - template: "grpcserver.tmpl"
    outputpath: "grpc/server/{FILE}_server.go"
  - template: "gateway.tmpl"
    outputpath: "gateway/{FILE}_gateway.go"
  - template: "grpcclient.tmpl"
    outputpath: "grpc/client/{FILE}_client.go"
  - template: "extpb.tmpl"
    outputpath: "{FILE}.pb.ext.go"
  - template: "apisrvbackends.tmpl"
    outputpath: "../exports/apiserver/backends.go"
  - template: "apigwservices.tmpl"
    outputpath: "../exports/apigw/services.go"
