---
targets:
  test: ["sh", "-c", "cd /sw && make pull-assets && cd storage/offload && bazel build ... && /sw/bazel-bin/storage/offload/pnso_offloader -t 10 -m 0xF; ret=$?; exit $ret" ]
  osal_test: ["sh", "-c", "cd /sw && make pull-assets && cd storage/offload && bazel build ... && bazel run src/osal:osal_test; ret=$?; exit $ret" ]
  sim_gtest: ["sh", "-c", "cd /sw && make pull-assets && cd storage/offload && bazel build ... && bazel test src/sim/test/gtests:all; ret=$?; exit $ret" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/storage/offload"
rebase: true

#warmd:
#  target: [ "sh", "-c", "cd /sw/test/suites/offload_klm && go run offload_klm.go" ]
#  create:
#    image: build-13
#    count: 1
#    resources:
#      cpus: 4
#      memory: 8
#
#  provision:
#    username: vm
#    password: vm
#   # additional vars to pass to ansible.
#    vars:
