---
targets:
  venice: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && TRACKER_URL=\"tracker.test.pensando.io\" make && ./tools/scripts/check-local-files.sh" ]
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
