---
version: 2.0
targets:
  venice:
    commands: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make && ./tools/scripts/check-local-files.sh" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"
rebase: true
